ROCmSoftwarePlatform/MIOpen

- driver/conv_driver.hpp
- src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_ncdhw_kczyx_nkdhw.hpp
- src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v4r1_ncdhw_kczyx_nkdhw.hpp
- src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v1r1_ncdhw_kczyx_nkdhw.cpp
- src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_data_implicit_gemm_v4r1_ncdhw_kczyx_nkdhw.cpp
- src/ocl/convolutionocl.cpp
- src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
- src/solver/conv_hip_implicit_gemm_bwd_data_v4r1.cpp
Implicit GEMM 3D backward data V4R1 and V1R1
> Implicit GEMM 3D backward data V4R1 and V1R1

- src/include/miopen/sqlite_db.hpp
- src/kern_db.cpp
> Handle uninstalled kernel database

- src/include/miopen/sqlite_db.hpp
- src/kern_db.cpp
- src/sqlite_db.cpp
> Resolve SQLite Out of memory error

- src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp
- Enforce loop unroll in xdlops gemm
- Workaround the performance issue ([SWDEV-229564](http://ontrack-internal.amd.com/browse/SWDEV-229564)) for the llvm intrinsic
> Unrolling the loop in xdlops GEMM

- src/solver/conv_hip_implicit_gemm_v4r4.cpp
> remove addtional parenthese

- src/ocl/convolutionocl.cpp
It fixes the bug reported in #199
> Fix backward weight igemm kernel time bug

- test/conv_common.hpp
The first two commits of this branch are expected to resolve issue #218. 
- Fixed: `test_immed_conv` always tests Find mode for Forward.
- Stopped using the WS size reported by Immediate mode during Find mode testing.
- `test_immed_conv`, Forward: Don't use Immediate GWSS. Remove extra `sort`. Some refactor.
- Properly implement check of Immediate GWSS results in the test.
> [test_immed_conv][test_conv] Fixes related to workspace size etc.

- test/CMakeLists.txt
See issue: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/226
> Disabled 2 configs.

- README.md
- doc/src/DebugAndLogging.md
- doc/src/releasenotes.md
- Added release notes
- Added check numerics documentation
> Update release notes for 2.5 

- Jenkinsfile
Reverts changes from [this commit](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/441bb75eabc2d0eeff42fbfc72b4e961693a662b).
Added Aux parallel stage.
> Reactivate static build tests. 

- src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
- Fixed incorrect vector_load (GEMM_B_BLOCK_COPY_SRC_DATA_PER_READ_GEMM_N) in v4r4_gen solver with dilation_w > 1
> [Hotfix] fix vector_load in v4r4_gen solver for dilation_w > 1

- driver/conv_driver.hpp
Fixes issue #264 originated from #172. Resizing of WS to suit needs of Find() calls was missing.
I need this asap to resume performance/correctness testing that I do from time to time with certain PRs (for ex. #233 and #293 are awaiting this right now)
> [driver] Fix wrong WS passed to Backward and WrW Find() calls.

- src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
> [WORKAROUND] Disabled ConvHipImplicitGemmBwdDataV1R1 for BF16.

- src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
- src/solver/implicitgemm_util.hpp
- Added a whitelist to check the validation of xdlopsGemm
- Fixed potential failures in the tuning process due to holes in the original check
> Refactored xdlops validation in the iGemm solver

- src/sqlite_db.cpp
> Fix SQLite `std::logic_error`

- src/ocl/dropoutocl.cpp
Dropout is used by dropout and rnn/lstm/gru paths and this change will affect relevant paths.
> Dynamic kernel: dropout

- src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
- test/CMakeLists.txt
1. remove unapplicable case in test_conv_igemm_dynamic_small.
2. update reduction groups' computation for solver ConvAsmImplicitGemmV4R1DynamicWrw.
> Dynamic igemm wrw update

- Jenkinsfile
- hip-clang.docker
Also, bump hip-clang version to ROCm 3.7.
> Make gfx908 tests use hip-clang docker

- src/kernels/MIOpenPoolingBwd.cl
> fix pooling bwd index error

- src/convolution.cpp
> [fix] Context configuration in GetWorkSpaceSize

- install_deps.cmake
This PR will look for ROCm's clang for CC compilation if it can and if CC / CMAKE_CC_COMPILER is not set.
> Set the CC compiler to /opt/rocm/llvm/bin/clang if available

- Jenkinsfile
This will help improve readability and also we can add more parameters easily.
> Use named params for buildJob

- src/batch_norm.cpp
- src/include/miopen/batch_norm.hpp
- src/ocl/batchnormocl.cpp
Workaround its disable variant 4 until debugging complete.
http://ontrack-internal.amd.com/browse/SWDEV-253606
> Workaround for SWDEV-253606

- CMakeLists.txt
For dependency issue: http://ontrack-internal.amd.com/browse/SWDEV-254578
> Update package dependencies to rocm-clang-ocl and hip-rocclr

- CMakeLists.txt
> Look for rocblas when installing miopen-hip

- Jenkinsfile
This gives us more control on how git commit statuses are updated.
> Use git status wrapper for jenkins

- src/CMakeLists.txt
- src/include/miopen/solver.hpp
- src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.hpp
- src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.cpp
- src/mlo_dir_conv.cpp
- src/solver.cpp
- src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
resnet50 first layer fp16 is 8TF,
this kernel is 28TF
> [igemm] this kernel can support resnet50 first layer wrw

- src/solver/conv_asm_dir_BwdWrW3x3.cpp
W/A for #532
@Kirpich30000 to review please
> [WORKAROUND] Disable ConvAsmBwdWrW3x3 for stride >= 2 && gfx9

- src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
- Resolved issue #546
- Fixed a bug in the tuning of v4r5 via adding check the availability of N for tensor contraction
> Fixed iGemm v4r5 tuning

- CMakeLists.txt
For this feature request:
http://ontrack-internal.amd.com/browse/SWDEV-254576
> Explicit conflict hip and opencl backends on package install

- src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
> [igemm]fix issue 427(don't drop small kpack*kperblock for all cases)

- src/kernels/MIOpenConvBwdBias.cl
- src/ocl/convolutionocl.cpp
This PR intends to convert convbwdbias kernel into a dynamic format.
> Dynamic convbwdbias

- src/include/miopen/oclkernel.hpp
- src/kernels/MIOpenUtilKernels4.cl
- src/ocl/convolutionocl.cpp
- src/ocl/utilocl.cpp
- src/ocl_kernel.cpp
- Convert transpose kernels in MIOpenUtilKernels4.cl to dynamic kernels (Issue #482)
> Dynamic transpose kernels

- src/conv/invokers/impl_gemm_dynamic.cpp
This fix [SWDEV-258416](http://ontrack-internal.amd.com/browse/SWDEV-258416), by clear the input gradient buffer before launch bwd kernel
> fix nan while training by conditionally clear input gradient tensor before launch bwd kernel

- src/include/miopen/solver.hpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
This PR is for the post review of  adding vector-load tune parameter, previous pr is: [pr347](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/347)
the related issue link is here: [issue387](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/387)
> post review of adding vector-load tune parameter

- src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Error msg in EuristicInit (called by IsApplicable) should really just be warning message
> Remove wrong error message in HIP-iGEMM

- src/hipoc/hipoc_program.cpp
- Fix for CO v4 version auto-detection introduced in #582.
- Fix for CO-option-syntax auto-detection introduced in #582.
- Introduced `MIOPEN_DEBUG_OPENCL_ENFORCE_CODE_OBJECT_OPTION` (undocumented intentionally)
> [COv4] Fix code object v4 support

- src/solver/conv_MP_bidirectional_winograd.cpp
> fix MP_winograd warning

- src/include/miopen/solver.hpp
- src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
This PR fix iGEMM wrw v4r4 tuning failure on gfx908, origin from #598 
Change:
Add spare to wrw v4r4 solver
> Fix iGEMM wrw v4r4 tuning failure on gfx908

- src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
- Disabled igemm_bwd_v4r1_xdlops
> disabled igemm bwd v4r1 xdlops

- src/solver/conv_asm_1x1u.cpp
> Disable AsmConv1x1U for gfx8 to resolve #135

- src/solver/conv_ocl_dir2Dfwd.cpp
- src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
> Fix kernel hit miss

- src/solver/conv_asm_3x3u.cpp
Partially resolves issue #609.
> ConvAsm3x3U: limit i/o buffers to 4GiB

- src/ocl/batchnormocl.cpp
Adding workaround fix for GFX1030 ASM kernel
> Adding batchnorm fix for GFX1030

- src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
- Add a comment following workaround rules for tracking the hotfix (PR #657) of issue #659
> Post_PR657: Add workaround comment

- src/include/miopen/solver.hpp
- src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
this PR is the same with 601,but add more protection, so drop 601 now
we add more protection to some corner cases ,and prevent invoker not calling isValidConfig
btw, increase the tuning range
> [igemm]fix tuning paramter of spare(issue 598 and issue 636)

- src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp
same as #671 for develop, but this one is for rocm-4.0.1
> fix issue 650 for rocm-4.0.1

- src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp
Fixing issue #650. 
Beware of the culprit
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/650#issuecomment-754979896
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/650#issuecomment-756987392
> fix issue 650 for develop

- hip-clang.docker
Instead of using the tip of master like we have been using.
> Use versioned rocm-cmake that comes with ROCm

- requirements.txt
Update clang-ocl & rocm-cmake version
> Update clang-ocl & rocm-cmake version

- src/convolution.cpp
- src/include/miopen/convolution.hpp
- src/include/miopen/find_solution.hpp
- src/include/miopen/mlo_internal.hpp
- src/mlo_dir_conv.cpp
> Get work space sizes update

- src/ocl/handleocl.cpp
- test/get_handle.hpp
- test/handle_test.cpp
- Resolves issue #703.
- Updates handle test to check if implementation of `miopenCreateWithStream()` works.
> [HOTFIX] Fix miopenCreateWithStream for OCL BE (issue 703)

- CMakeLists.txt
Fixes issue: [SWDEV-269156](http://ontrack-internal.amd.com/browse/SWDEV-269156)
> Check  for programs with CMAKE_INSTALL_PREFIX

- src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
- To workaround issue #670 
- Disable DIRECT_OCL_WRW1X1 for Navi21
> [OCL] Disable DIRECT_OCL_WRW1X1 to workaround failures for Navi21

- src/md_graph.cpp
> [Fusions] Selection of fused asm 1x1 kernel restricted to appropriate targets.

- src/binary_cache.cpp
Let's stop cluttering the console. What will be output instead of kernel source:
```
...Loading binary for: 20deccc8f9c9a83ad6c4f344986e80a0.o size=15374...
```
> [OCL BE][NFC] Dump md5 hash instead of MIOpenGEMM kernels source at log level 6

- driver/CBAInferFusion_driver.hpp
- driver/activ_driver.hpp
- driver/bn_driver.hpp
- driver/conv_driver.hpp
- driver/ctc_driver.hpp
- driver/dropout_driver.hpp
- driver/gemm_driver.hpp
- driver/lrn_driver.hpp
- driver/pool_driver.hpp
- driver/reduce_driver.hpp
- driver/rnn_driver.hpp
- driver/softmax_driver.hpp
- driver/tensorop_driver.hpp
Get rid of annoying thousands of warning lines.
> [NFC][MIOpenDriver] Fix build warnings with ROCm 4.0

- requirements.txt
- test/lstm_common.hpp
> [Workaround] Skip opencl lstm test for Issue #692

- Jenkinsfile
added information about used node in stage output
> [Jenkins] information about current node

- test/mdgraph.cpp
- workaround for issue #763
- skip unsupported fusion algorithms for gfx1030
> [WORKAROUND] test_mdgraph: skip unsupported algo for gfx1030

- Jenkinsfile
This ~should~ could save another couple of hours for each CI job.
> [CI] Optimize out unnecessary image rebuilds that affect Static checks. Add explicit notion of "default image name".

- src/gemm_v2.cpp
To jira ticket http://ontrack-internal.amd.com/browse/SWDEV-275854
> Add latest rocblas api flag (SWDEV-275854)

- Dockerfile
- src/hip/handlehip.cpp
- src/hipoc/hipoc_program.cpp
- src/include/miopen/mlir_build.hpp
- src/include/miopen/solver.hpp
- src/mlir_build.cpp
- src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
- src/solver/conv_hip_implicit_gemm_mlir_cpp_bwd.cpp
- src/solver/conv_hip_implicit_gemm_mlir_cpp_fwd.cpp
- src/solver/conv_hip_implicit_gemm_mlir_cpp_wrw.cpp
- src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
This PR address https://github.com/ROCmSoftwarePlatform/MIOpen/issues/803
* Finished fwd/bwd/wrw solvers
* Decoupled the MLIR fwd solver from base class
* Refactor from Mlir -> Miir, used latest Miir API
> Making MLIR solver obtain launch params from API

- test/mdgraph.cpp
- Add supported arch list for winograd and asm fusion algo, and skip unsupported arch
> [tests] test_mdgraph: skip unsupported arch

- Jenkinsfile
This PR is prerequisite of PR #556 
I've investigated @pfultz2 's suggestion about using keyword in commits to control stage on/off. It requires setting changes on node side. I don't think we want to make any changes of the nodes' properties since this whole solution is adhoc for miopentensile. This strategy provides param control from stage level rather than step level. Open to requests of major revises.
> add param to control CI stages

- Jenkinsfile
Dy default, disable Full MIOpenTensile-Latest tests but enable Smoke tests. This saves 1.5...3 hours per each CI job.
Anyone can manually enable Full tests if necessary, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/556#discussion_r615164672
> [CI] MIOpenTensile: Switch OFF full tests by default, add smoke tests.

- test/CMakeLists.txt
This is W/A for #874 to unblock CI.
> [WORKAROUND][CI] Issue 874, failures of test_conv_embed_db

- src/kernels/conv1x1u_stride2.s
* gfx906, rocm 4.0
* gfx90a, only kernel compilation
> Direct Asm 1x1 stride2 fixes for gfx90a

- Dockerfile
- Jenkinsfile
> adopt public resource

- test/ctc.cpp
> [CTC] Fix undefined behavior

- src/convolution.cpp
Resolves #904 
@JehandadKhan Please check if this (positively or negatively) affects Tuna, thanks.
> IsWinograd3x3SupportedAndFast() changed to obey MIOPEN_DEBUG_FIND_ONLY_SOLVER

- src/include/miopen/solver/implicitgemm_util.hpp
> Change gcd() implementation to avoid too deep recursion

- install_deps.cmake
This will install boost with the correct URL.
Should resolve #856.
> Install deps using cget instead of cmake-get

- src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
Urgent W/A for https://ontrack-internal.amd.com/browse/SWDEV-286774
> [HOTFIX] Workaround for SWDEV-286774. Disable ConvAsmImplicitGemmGTCDynamicBwdXdlops.

- src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
- test/CMakeLists.txt
> [HOTFIX][WORKAROUND] Disable ConvAsmImplicitGemmGTCDynamicWrwXdlops for FP16

- src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
- test/CMakeLists.txt
Resolves #946.
Fix kernel selection error for c or k padding cases with single batch.
<details> <summary><b><i>test script</i></b> </summary> 
```
export MIOPEN_LOG_LEVEL=0
export MIO_TFLAGS="--disable-forward --disable-backward-data --disable-verification-cache -v"
export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvAsmImplicitGemmGTCDynamicWrwXdlops 
./bin/test_immed_conv2d --half --cmode conv --pmode default --group-count 1 --enable-fdb 1 --input 1, 3, 224, 224 --weights 1, 3, 7, 7 --pads_strides_dilations 1 1 2 2 3 3 --trans_output_pads 0 0 ${MIO_TFLAGS}
./bin/test_immed_conv2d --half --cmode conv --pmode default --group-count 1 --enable-fdb 1 --input 1, 3, 224, 224 --weights 1, 3, 7, 7 --pads_strides_dilations 1 1 2 2 2 1 --trans_output_pads 0 0 ${MIO_TFLAGS}
./bin/test_immed_conv2d --half …
```
> [MI100][Dynamic Asm iGemm WrW] Fix kernel selection error for c or k padding cases with single batch, remove W/A for issue 946

- Jenkinsfile
This PR is a pre-requisite of miopen-tensile opencl backend project.
This project requests check in of new test stages, while Jenkinsfile is at the edge of legal upper limit. This PR puts repeatedly used steps into methods outside of the pipeline to reduce the size of the file. This PR will save some space for adding opencl tests for tensile.
> [TESTS] Encapsulate Jenkins runDockerJob

- src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
- test/CMakeLists.txt
> [MI100]fix issue 980-fix kernel selection logic for k-padding cases

- test/network_data.hpp
Finally resolves #915, see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/915#issuecomment-839212864
> Adding missing test vectors which caused failures (partial fix for SWDEV-291891)

- src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
> [HOTFIX] Fix bug ConvHipImplicitGemmBwdDataV4R1Xdlops (SWDEV-291202)

- src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp
- test/CMakeLists.txt
fix #999 
Fix kernel selection issue with asm igemm wrw pass.
> [vega][fp32]fix vega asm igemmwrw kernel selection bug

- test/CMakeLists.txt
> Add regression test for issue 540

- test/CMakeLists.txt
> [TESTS] Add regression tests for SWDEV-291574

- test/handle_test.cpp
Added gfx90a support for test handle file.
> Add gfx90a support for test handle

- driver/activ_driver.hpp
- driver/tensor_driver.hpp
- src/CMakeLists.txt
- src/include/miopen/activ/solvers.hpp
- src/include/miopen/find_solution.hpp
- src/ocl/activ_ocl.cpp
- src/solver.cpp
- src/solver/activ/fwd_0.cpp
- src/solver/activ/fwd_1.cpp
- test/activation.cpp
- test/tensor_holder.hpp
It implements the second forward activation solver, complete with an invoker.
An option has been added to the activation driver to make tensors not packed so that the solver would be invoked.
> [NFC] Second activation fwd solver

- src/solver.cpp
Fixed build error. The reason is that #967 wasn't updated from develop after merging of #1017
> [HOTFIX] Fix incorrect registration of ActivFwdSolver1 due to desync between #1017 and #967

- Jenkinsfile
> [TESTS][MI100][MLIR] Fix issue #1025 MLIR is not tested on gfx908

- src/CMakeLists.txt
- src/activ/problem_description.cpp
- src/include/miopen/activ/invoke_params.hpp
- src/include/miopen/activ/problem_description.hpp
- src/include/miopen/activ/solvers.hpp
- src/ocl/activ_ocl.cpp
- src/solver.cpp
- src/solver/activ/bwd_0.cpp
It implements the first backward activation solver, complete with an invoker.
Performance testing is complete and doesn't show any difference to develop.
> [NFC] Activation backward solver 0

- src/include/miopen/generic_search.hpp
- src/include/miopen/solver.hpp
- src/solver/conv_asm_1x1u.cpp
- src/solver/conv_asm_1x1u_stride2.cpp
- src/solver/conv_asm_3x3u.cpp
- src/solver/conv_asm_dir_BwdWrW1x1.cpp
- src/solver/conv_asm_dir_BwdWrW3x3.cpp
- src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
- src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
- src/solver/conv_asm_implicit_gemm_gtc_perf_config.cpp
- src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
- src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp
- src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp
- src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
- src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
- src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp
- src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
- src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
- src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
- src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
- src/solver/conv_winoRxS_f2x3.cpp
- src/solver/conv_winoRxS_f3x2.cpp
Implements ticket #388 (also promised at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1018#issuecomment-870969779). Some non-robust code eliminated at once.
Added many reviewers just to inform all potentially interested.
> [NFC] ConvolutionContext made accessible in SetNextValue() 

- Jenkinsfile
- test/CMakeLists.txt
- test/driver.hpp
https://ontrack-internal.amd.com/browse/SWDEV-295448
> [TESTS] Set MIOPEN_TEST_LIMIT to 2 by default (SWDEV-295448)

- src/kernels/MIOpenBatchNormActivBwdPerAct.cl
- src/kernels/MIOpenBatchNormActivBwdSpatial.cl
- src/kernels/MIOpenBatchNormActivFwdTrainSpatial.cl
- src/kernels/MIOpenBatchNormBwdSpatial.cl
- src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
- src/kernels/batchnorm_functions.h
Addressed compile time requests from this issue.
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1036
> [BN][Navi21] Get rid of "#undef __AMDGCN__"

- Dockerfile
- src/solver/conv_mlir_igemm_bwd.cpp
- src/solver/conv_mlir_igemm_bwd_xdlops.cpp
These checks have been moved to MLIR tuning parameter pass.
> [MLIR] Remove gemm size checks from ConvMlirIgemmBwd and ConvMlirIgemmBwdXdlops

- test/CMakeLists.txt
1) Most of test disabled on gfx908 are now enabled.
2) gfx908 is enabled by default for custom tests.
> [gfx908][TESTS] Adding a number of tests

- driver/reduce_driver.hpp
- src/reducetensor_api.cpp
This is mainly for issue [1041](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1041).
> [Driver] Fix LogCmdRedux() for double reduction

- Dockerfile
> [Jenkins] update ROCm gpg key to permanent location

- src/include/miopen/float_equal.hpp
> [ArchLinux][GCC-11][OCL] Add missing limits header fix #1083

- src/include/miopen/any_solver.hpp
addressing comments in #1117
----
@atamazov: Formally speaking, this resolves issue #1122
> [TUNA] IsTunable code quality 

- test/dropout.cpp
- test/dropout_util.hpp
To save CI resource
Issue #1128
> Reduce number of dropout test case

- src/CMakeLists.txt
- src/include/miopen/batchnorm/solvers.hpp
- src/ocl/batchnormocl.cpp
- src/solver.cpp
- src/solver/batchnorm/forward_per_activation.cpp
- src/solver/batchnorm/forward_spatial_multiple.cpp
- src/solver/batchnorm/forward_spatial_single.cpp
This implements the third bnorm solver.
Also, I realized that I have accidentally reverted their names initially, but otherwise the code was still correct. This only affects logging, because BN does not use find-db and perf-db.
My tests passed, running ones provided by @muralinr currently. I will provide an update on their results today.
> [NFC] The third batchnorm solver

- src/CMakeLists.txt
- src/include/miopen/batchnorm/solvers.hpp
- src/ocl/batchnormocl.cpp
- src/solver/batchnorm/backward_spatial_single.cpp
Both my and @muralinr benchs have passed. No perf or build parameters difference.
> Backward spatial single-kernel solver

- src/CMakeLists.txt
- src/kernels/Conv_Winograd_v21_1_2_f3x2_fp16_dot2_edc_stride1_group.s
- src/kernels/Conv_Winograd_v21_1_2_gfx90a_f3x2_fp16_dot2_edc_stride1_group.inc
- src/solver/conv_winoRxS_f3x2.cpp
This PR adds Winograd f3x2 FP16 support for gfx90a.
This kernel internally uses FP32 mathfor computations and should not lead to precision issues.
Partially resolves issue ROCmSoftwarePlatform/MIOpen-internal#2.
- rocm 4.3.1, gfx90a
<details>
<summary>Test cases</summary>
-W | -H | -c | -n | -k | -x | -y | -q | -p | -u | -v | -F | -t | -V | -g
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 1 | 1 | 1 | 1
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 1 | 1 | 1 | 4
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 2 | 1 | 1 | 1
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 2 | 1 | 1 | 4
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 4 | 1 | 1 | 1
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 4 | …
> [gfx90a] Winograd f3x2 fp16 support

- src/CMakeLists.txt
- src/kernels/Conv_Winograd_v21_1_2_fp16_dot2_edc_dilation2.s
- src/kernels/Conv_Winograd_v21_1_2_fp16_dot2_edc_dilation2_group.s
- src/kernels/Conv_Winograd_v21_1_2_fp16_dot2_edc_stride1.s
- src/kernels/Conv_Winograd_v21_1_2_fp16_dot2_edc_stride1_group.s
- src/kernels/Conv_Winograd_v21_1_2_fp16_dot2_edc_stride2.s
- src/kernels/Conv_Winograd_v21_1_2_fp16_dot2_edc_stride2_group.s
- src/kernels/Conv_Winograd_v21_1_2_gfx90a_fp16_dot2_edc_dilation2.inc
- src/kernels/Conv_Winograd_v21_1_2_gfx90a_fp16_dot2_edc_dilation2_group.inc
- src/kernels/Conv_Winograd_v21_1_2_gfx90a_fp16_dot2_edc_stride1.inc
- src/kernels/Conv_Winograd_v21_1_2_gfx90a_fp16_dot2_edc_stride1_group.inc
- src/kernels/Conv_Winograd_v21_1_2_gfx90a_fp16_dot2_edc_stride2.inc
- src/kernels/Conv_Winograd_v21_1_2_gfx90a_fp16_dot2_edc_stride2_group.inc
- src/solver/conv_winoRxS_f2x3.cpp
This PR adds Winograd f2x3 FP16 support for gfx90a. 
These kernels use FP32 math internally for computations and should not lead to precision issues.
Partially resolves issue ROCmSoftwarePlatform/MIOpen-internal#2.
- gfx90a, rocm 4.3.1
<details>
<summary>Test cases</summary>
-W | -H | -c | -n | -k | -x | -y | -q | -p | -u | -v | -F | -t | -V | -g
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 1 | 1 | 1 | 1
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 1 | 1 | 1 | 4
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 2 | 1 | 1 | 1
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 2 | 1 | 1 | 4
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 4 | 1 | 1 | 1
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | 4 …
> [gfx90a] Winograd f2x3 fp16 support

- Jenkinsfile
This could save some testing time in certain cases, e.g. when you would like to replace some FP16 workaround with a full-blown fix and test it quiclky.
> [CI] Possibility to test for specific datatype

- Jenkinsfile
Leftover after #1190 and #1191
> [CI] Fix: Add datatype for the new 'Fp32 Hip All gfx90a Xnack+' stage

- Jenkinsfile
- src/find_db.cpp
- src/include/miopen/execution_context.hpp
#1185 
The recursive directory iterator descends into directories and likely has some faulty logic which gets triggered on the CI. Furthermore recursion is not required.
> [Enhancement] remove recursive dir iterator

- Jenkinsfile
Both CI throughput and quality degraded after #1197. Please review & merge ASAP.
> [HOTFIX] Revert some temp commits accidentaly merged from  #1197 "[Enhancement] remove recursive dir iterator" 

- src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
W/A for #1206 for 4.5 release.
> [HOTFIX][WORKAROUND] W/A for issue 1206. Disable ConvHipImplicitGemmBwdDataV4R1Xdlops by default.

- src/include/miopen/find_solution.hpp
- src/ocl/activ_ocl.cpp
- src/ocl/batchnormocl.cpp
Primitive calls contain a lot of similar code. I have moved it to a function to reduce duplications. The same function would be used in other primitives.
> [NFC] Cleaned-up batchnorm and activation

- test/CMakeLists.txt
> [CI][Tests] add unit test for asm igemm when K=2x

- src/kernels/conv1x1u.s
- src/kernels/conv1x1u_bias_activ.s
- src/kernels/conv1x1u_stride2.s
- src/kernels/conv1x1wrw.s
This PR fixes Direct conv 1x1 for gfx90a. Resolves issue https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/3.
Tested using docker container and command provided in https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/3.
- gfx90a, rocm 4.3.1
<details> <summary>ConvAsm1x1U</summary>
-W | -H | -c | -n | -k | -x | -y | -q | -p | -u | -v | -t | -i | -V | -g | dir | type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --- | ----
4 | 4 | 576 | 32 | 128 | 1 | 1 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | fwd/bwd | FP16/FP32
4 | 4 | 576 | 64 | 128 | 1 | 1 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | fwd/bwd | FP16/FP32
4 | 4 | 608 | 32 | 128 | 1 | 1 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | fwd/bwd | FP16/FP32
4 | 4 | 608 | 64 | 128 | 1 | 1 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | …
> [gfx90a][tuning] Fix build errors during tuning in Direct conv1x1 kernels

- src/CMakeLists.txt
- src/include/miopen/datatype.hpp
- src/include/miopen/pooling.hpp
- src/include/miopen/pooling/invoke_params.hpp
- src/include/miopen/pooling/problem_description.hpp
- src/include/miopen/pooling/solvers.hpp
- src/include/miopen/solver_id.hpp
- src/ocl/pooling_ocl.cpp
- src/pooling/problem_description.cpp
- src/solver.cpp
- src/solver/pooling/forward2d.cpp
- src/solver/pooling/forwardNd.cpp
This contains two solvers at once, but they are split to separate commits.
Testing complete, no meaningful deviations.
> Pooling forward solvers (except GetWorkspaceSize)

- Jenkinsfile
> [TESTS][OCL][MI100][MI200] Fix OpenCL Full tests to run on MI100/200

- addkernels/addkernels.cpp
- src/CMakeLists.txt
The problem is described in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1322
> [NFC][addkernels] Fix compiler warnings [-Wreserved-identifier]

- driver/calcerr.hpp
- driver/conv_verify.hpp
- driver/mloConvHost.hpp
- driver/mloNeuronHost.hpp
- driver/mloNormHost.hpp
- driver/mloPoolingHost.hpp
- src/include/miopen/mlo_internal.hpp
The problem is described in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1322
> [NFC] Reduce compiler warnings [-Wreserved-identifier]

- src/solver/conv_asm_1x1u.cpp
- src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
The problem is described in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1322
> [NFC][solvers] Fix compiler warnings [-Wreserved-identifier]

- src/binary_cache.cpp
- src/hip/handlehip.cpp
- src/include/miopen/binary_cache.hpp
- src/include/miopen/generic_search.hpp
- src/include/miopen/handle.hpp
- src/include/miopen/kernel_cache.hpp
- src/kernel_cache.cpp
- src/nogpu/handle.cpp
- src/ocl/handleocl.cpp
- Bugfix: Resolves https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1221#pullrequestreview-840041412
- Perf optimization for DEV builds: Resolves https://github.com/ROCmSoftwarePlatform/MIOpen/pull/533#discussion_r513800752
I recommend cherry-picking this into 5.0
> Fix for PR 1221. After tuning, remove benchmarked Programs only (related to: SWDEV-304151)

- src/kernels/conv3x3.s
fixes #1374 
Please refer to #1374  for details of this pr.
> [BUG] Resolve the compilation error of conv3x3.s

- driver/InputFlags.cpp
- driver/InputFlags.hpp
UPD by @atamazov:
This is expected to resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1282#pullrequestreview-850574173.
----
- Post Merge review comments added.
- Formatting
- Function name & i/p parameter names are changed.
Signed-off-by: Sujatha Phatak <sujatha.phatak@amd.com>
>    [driver] #1379 - Post Merge Review Update

- driver/conv_driver.hpp
- src/include/miopen/tensor_layout.hpp
This is regarding the fix for below issue
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1311 
@JehandadKhan @atamazov @junliume   @cderb please review
> layout_flag_error_handle

- Jenkinsfile
- driver/InputFlags.cpp
- driver/conv_driver.hpp
- src/comgr.cpp
- src/conv/invokers/impl_gemm_dynamic.cpp
- src/gemm_v2.cpp
- src/include/miopen/activ/solvers.hpp
- src/include/miopen/batchnorm/solvers.hpp
- src/include/miopen/conv/asm_implicit_gemm.hpp
- src/include/miopen/generic_search.hpp
- src/include/miopen/solver.hpp
- src/include/miopen/sqlite_db.hpp
- src/include/miopen/tensor_layout.hpp
- src/kernels/MIOpenBatchNormBwdSpatial.cl
- src/kernels/MIOpenBatchNormFwdTrainSpatial.cl
- src/ocl/batchnormocl.cpp
- src/solver/batchnorm/backward_spatial_single.cpp
- src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
- src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
- src/solver/conv_asm_implicit_gemm_gtc_perf_config.cpp
- test/bn_spatial_nhwc_test.cpp
- test/ford.hpp
- test/solver.cpp
"Clang format" stage was fixed
Additional changes: formatting all code according to the .clang-format.
> [Jenkins] Fix "clang-format" stage

- include/miopen/miopen.h
Batchnorm inference API documentation is updated with more details
> [DOC][NFC] Batchnorm inference API documentation update

- src/buffer_info.cpp
Resolve #1458 
reduce multi buffer size by using offset of last buffer plus last buffer size
> [issue 1458]reduce multi-buffer size

- CMakeLists.txt
disable hipRTC by default in mainline
> [Mainline][SWDEV-327397][HotFix] disable hipRTC by default

- src/ocl/batchnormocl.cpp
As suggested, added conditions to every check where a buffer may be nullptr.
Fixes #1442
> [BN] Fixed numeric checks for valid nullptr buffers

- src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
W/A for #1477. 
@junliume Please let me know if it works or not. Thanks.
> [WORKAROUND][BF16][MI200] Disable ConvHipImplicitGemmBwdDataV4R1Xdlops due to compiler issue (W/A for SWDEV-329642)

- test/conv_common.hpp
This PR is expected to fix the issue #1494.
> [Bug fix] Passing "--weight" flag to filter_dims.

- CMakeLists.txt
This PR updates the version of MIOpen post ROCm release 5.1
> Update MIOpen Version

- include/miopen/config.h.in
- requirements.txt
- src/exec_utils.cpp
- src/execution_context.cpp
- src/gemm_v2.cpp
- src/hip/handlehip.cpp
- src/hip/hip_build_utils.cpp
- src/hipoc/hipoc_program.cpp
- src/include/miopen/find_db.hpp
- src/include/miopen/handle.hpp
- src/include/miopen/mdg_expr.hpp
- src/include/miopen/mlo_internal.hpp
- src/include/miopen/op_kernel_args.hpp
- src/mlo_dir_conv.cpp
- src/ocl/convolutionocl.cpp
- src/ocl/fusionopbiasbnactivocl.cpp
- src/pooling.cpp
- src/readonlyramdb.cpp
- src/softmax_api.cpp
- src/solver/conv_bin_winoRxS.cpp
- src/solver/conv_ocl_dir2D11x11.cpp
Contineous work based on #1490
Also should fix #1489
> [Boost][JP-Ellis&Artem] Update Boost version to 1.79

- LICENSE.txt
- fin/LICENSE
Only License Wording changes
We should be able to bypass CI, I will let it through static checks and smokes though.
> [SWDEV-334271] Palamida scan remediation

- utils/install_precompiled_kernels.sh
> [MIOpenKernels] fix names for MIOpen precompiled kernels

- src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
- src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
- src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
- test/CMakeLists.txt
disable group conv for rocm5.2 staging
> [SWDEV-342188] [MSRCHA-236][W/A] disable group conv in asm igemm solver

- doc/src/conf.py
Modification was made as per Standard AMD Copyright Notice.
> SWDEV-303880 : updated copyright notice in miopen documentation

- src/comgr.cpp
Workaround for https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1648
> [WORKAROUND] [hipRTC] Warning issues with hipRTC_header.h

- src/kernels/MIOpenTensorKernels.cl
Added Tensor op changes when beta is zero.  Changes are limited to one file only.
> [Enhancement] Tensor op changes when beta is zero

- src/pooling_api.cpp
Command is now printed with args in a driver-accepted format, rather than old non supported one.
Fixes #1647.
> [Tests][Enhancement] Fix pooling command printing

- src/include/miopen/convolution.hpp
- src/ocl/convolutionocl.cpp
- test/conv_common.hpp
- test/driver.hpp
- test/gpu_conv.hpp
Prefer naive GPU kernels to verify convolution, fall back to CPU verification if the GPU kernel cannot be used.
cc @atamazov
> [Enhancement][Tests] GPU based verification for convolutions

- Jenkinsfile
- test/CMakeLists.txt
This PR makes the following changes
* Makes OpenCL stages optional by introducing a new parameter in the CI pipeline
* Merges the Full Test Stages together
* Adds retry option to GPU stages
> [CI] Make OpenCL stages optional and add retry

- src/solver/conv_winoRxS.cpp
This is expected to work around issue #1681.
@junliume `urgency_blocker`, `performance, bug`. `workaround`. Can you please also double check if this resolves the performance issue, thank you!
> [WORKAROUND][HOTFIX] W/A for #1681, "Performance drops after PR #1634"

- src/kernels/gfx90a6e.kdb
Tuning updates of fdb and kdb for mi250
> [ROCm 5.3][gfx90a6e] Tuning updates of fdb and kdb key configurations

- driver/pool_driver.hpp
This is a simple debug improvement for the pooling driver.
This was made as a side-tool while working on #1723.
> Added support for reading and dumping buffers in pooling driver.

- src/kernels/MIOpenPoolingBwd.cl
- src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp
Urgent issues in #1732 and #1733
> [HotFix] Fix build issues with #1732 and #1733

- src/include/miopen/any_solver.hpp
- src/include/miopen/find_solution.hpp
Fix conflict issues with #1713  and #1663 together
> [HotFix] Post merge fix for ConvolutionContext/Problem Split

- CMakeLists.txt
- Dockerfile
- Jenkinsfile
- requirements.txt
- src/include/miopen/any_solver.hpp
- src/include/miopen/find_solution.hpp
> [CK] Fix Composable Kernel dependency building and Enable by default

- src/conv/invokers/impl_gemm_dynamic.cpp
- src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
- src/include/miopen/solver.hpp
- src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp
- src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvAsmImplicitGemmV4R1DynamicBwd and ConvAsmImplicitGemmGTCDynamicBwdXdlops
> [Solvers] ConvAsmImplicitGemmV4R1DynamicBwd, ConvAsmImplicitGemmGTCDynamicBwdXdlops: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/solver.hpp
- src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvAsmImplicitGemmGTCDynamicWrwXdlops
> [Solvers] ConvAsmImplicitGemmGTCDynamicWrwXdlops: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/solver.hpp
- src/include/miopen/solver/conv_direct_naive_conv.hpp
- src/solver/conv_direct_naive_conv.cpp
- src/solver/conv_direct_naive_conv_bwd.cpp
- src/solver/conv_direct_naive_conv_fwd.cpp
- src/solver/conv_direct_naive_conv_wrw.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvDirectNaiveConv solvers
> [Solvers] ConvDirectNaiveConv solvers: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/solver.hpp
- src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvAsmImplicitGemmGTCDynamicFwdXdlops
> [Solvers] ConvAsmImplicitGemmGTCDynamicFwdXdlops: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/solver.hpp
- src/solver/fft.cpp
PR splits ConvolutionContext and ProblemDescription inside fft solver
> [Solvers] FFT: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/solver.hpp
- src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvOclBwdWrW1x1
> [Solvers] ConvOclBwdWrW1x1: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/solver.hpp
- src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvOclBwdWrW53
> [Solvers] ConvOclBwdWrW53: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/any_solver.hpp
ctx.problem should be ctx for GetPerfCfgParams passing method
#1769
> Fix for GetPerfCfgParams call

- src/include/miopen/generic_search.hpp
- src/include/miopen/solver.hpp
- src/solver/conv_asm_1x1u.cpp
- src/solver/conv_asm_1x1u_bias_activ.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvAsm1x1U and ConvBiasActivAsm1x1U
> [Solvers] ConvAsm1x1U, ConvBiasActivAsm1x1U: split ConvolutionContext and ProblemDescription (stage 2)

- src/conv/invokers/impl_gemm_dynamic.cpp
- src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp
- src/include/miopen/solver.hpp
- src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC
> [Solvers] ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC: split ConvolutionContext and ProblemDescription (stage 2)

- src/include/miopen/solver.hpp
- src/include/miopen/solver/ck_utility_common.hpp
- src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvCkIgemmFwdV6r1DlopsNchw
> [Solvers] ConvCkIgemmFwdV6r1DlopsNchw: split ConvolutionContext and ProblemDescription (stage 2)
