doc/src/activation.rst
The function `miopenCreateActivationDescriptor` was missing in the documentation.
=> Adding missing function to documentation

src/include/miopen/sqlite_db.hpp
This PR removes co-located files which are causing issue with permission, and restores the old behavior.
The rationale for this change was to share the directory with multiple dockers running MIOpen. However, we see many lock file creation failures in logs, furthermore if the user config directory is not present the lock file creation fails. 
Since, we are getting rid of this mechanism for SQLite pdb in a subsequent PR, it doesn't make sense to keep this and create issues.
=> Remove Co-located lock files

src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_nchw_kcyx_nkhw.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_nchw_kcyx_nkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_nchw_kcyx_nkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp, src/kernels/composable_kernel/include/utility/config.hpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_nchw_kcyx_nkhw_lds_double_buffer.cpp
On fp16 fwd pass, the rocprof metrics reported that our fetch size was much larger than fp32 and memory unit was busy. To reduce fetch size, we want to hit more L2. Changing workgroup scheduler has helped us hit more L2 as depicted in 2nd rocprof metrics.
MIOpenDriver convfp16 -n 64 -c 1024  -H 14 -W 14 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -g 1 -w 1 -t 1 -F 1
dispatch[0], gpu-id(0), queue-id(4), queue-index(0), tid(31056), grd(200704), wgr(256), lds(0), scr(0), vgpr(96), sgpr(48), fbar(0), sig(0x7f8483b7da80), kernel-name("gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_nchw_kcyx_nkhw_lds_double_buffer.kd")
SQ_WAVES (3136)
FETCH_SIZE (192237)
MemUnitBusy (80)
MemUnitStalled (2)
SQ_LDS_BANK_CONFLICT (16056320)
LDSBankConflict (22)
ALUStalledByLDS (0)
L2CacheHit (57)
After workgroup …
=> Change workgroup launch pattern for fp16 fwd

src/include/miopen/kern_db.hpp, src/include/miopen/sqlite_db.hpp, src/kern_db.cpp, src/sqlite_db.cpp
This PR improves the handling schema variation in Perf Db. Previously, we only checked the absence or presence of tables in the database. This PR adds the capability to inspect the columns of the tables ( if they exist in the database) and report any mismatch. If a mismatch is found, a warning is issued reporting the missing columns and access to the invalid database is disabled.
This PR does not result in any functionality or performance changes.
=> Improved error checking during db creation

driver/conv_driver.hpp, driver/dropout_driver.hpp, src/convolution.cpp, src/find_controls.cpp, src/include/miopen/find_controls.hpp, src/include/miopen/handle.hpp, src/ocl/convolutionocl.cpp
Moved from https://github.com/AMDComputeLibraries/MLOpen/pull/2200
- Added Fast Find mode (A.1 in https://github.com/AMDComputeLibraries/MLOpen/issue/2208)
- Added Hybrid Find mode (A.2 in https://github.com/AMDComputeLibraries/MLOpen/issue/2208)
- Controlled by the `MIOPEN_FIND_MODE` with syntax checks, numeric and symbolic values (case-insensitive) etc. Valid values:
- `NORMAL` or `1` or empty (undefined variable)
- `FAST` or `2`
- `HYBRID` or `3`
- ___TODO___ User documentation.
- ___TODO___ Make Hybrid mode the default (for Release non-DEV builds).
- ___TODO___ Merge user-find-db caching feature. Otherwise the wall time may suffer when the user-find-db becomes really big (usually it grows as the time passes).
- [Side product] Improved logging in Fwd/Bwd GWSS.
:bulb: The change is …
=> Merge Fast/Hybrid Find modes into develop

src/include/miopen/sqlite_db.hpp
During the cleanup of the Perf DB SQLite object it is possible that the database may be busy writing previous transactions and return busy. 
This PR addresses this case by reusing the appropriate logic already present in the database class.
=> Handle SQLITE_BUSY during object cleanup

src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_fwd_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_fp16_bfp16_wrw_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.cpp, src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
Change gemmkpack extraction logic for fp16/bfp16 group convolution to achieve vectorized reads in Matrix A along gemmK dimension in 3x3 resnext101 filter cases.  Upto 40% gains in resnext101 group configs.
=> Change kpack extraction for fp16 bfp16 group conv fwd

doc/src/convolution.rst, include/miopen/miopen.h
Removed redundant `@struct` that lead to annoying warnings due to issue in the compiler (moving comment blocks after definitions resolve the problem but that is not what we want).
Ubuntu 18.04.1 LTS, vanilla rocm-dkms 3.3-19.
=> [NFC] Removed redundant `@struct` from miopen.h

src/include/miopen/conv/problem_description.hpp, src/include/miopen/problem_description.hpp, src/solver/conv_ocl_dir2D_bwdWrW_2.cpp
Added condition in IsApplicable.
Fix for issue #142
=> Disabling ConvOclBwdWrW2  for asymmetric padding 

src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_gnchw_gkcyx_gnkhw.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_data_implicit_gemm_v1r1_xdlops_fp16_bfp16_nchw_kcyx_nkhw.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4_fp16_bfp16_nchw_kcyx_nkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r1_fp16_bfp16_nchw_kcyx_nkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_xdlops_fp16_bfp16_nchw_kcyx_nkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_fp16_bfp16.hpp, src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp, src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp, src/kernels/composable_kernel/include/utility/float_type.hpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.cpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_nchw_kcyx_nkhw_lds_double_buffer.cpp, src/kernels/float_types.h
There is a mixed use of "half" and "_Float16" in HIP kernel, but they are different type. Compiler team suggested using "_Float16" everywhere.
=> Change half to _Float16 type in composable kernel

src/include/miopen/execution_context.hpp, src/include/miopen/sqlite_db.hpp
If an empty path is passed as the perf-db target directory, this results in perf-db files with just the filename resulting in an empty directory path. Which causes `boost::create_directory` function to seg fault. 
This PR ensures that
* PDB path with only filename is not created
* Empty path is not passed to create directory
=> Fix empty path in perf db

src/include/miopen/kern_db.hpp, src/include/miopen/sqlite_db.hpp, src/kern_db.cpp, src/sqlite_db.cpp, test/sqlite_perfdb.cpp
Currently we are not linking in the static version of sqlite, however, when we link in the static version the test breaks when the symbols are hidden. This is because part of the sqlite code is in the header and some other code is in the cpp file which cause two different instances of sqlite to be used in the test which is a problem because of the global variables used in sqlite
We need to put all the code that calls the sqlite api in cpp files, this should also improve compile time
Resolves #184
=> Moving SQLite calls to cpp files

Jenkinsfile, src/ocl/convolutionocl.cpp, src/ocl/gcn_asm_utils.cpp, test/find_db.cpp
- Workaround for SWDEV-233338
- Formalized workaround for SWDEV-220166
- Better logging
- Issue `Error` message if assembler is not available. Substantial performance regression is highly likely, and we consider that as serious defect.
Manually tested.
=> Workaround for SWDEV-233338

CMakeLists.txt
Change needed to resolve broken RPM install for miopen-hip and miopen-opencl.
=> Update CMakeLists.txt: : rocm-opencl-devel to rocm-opencl-dev for RPM Requires

CMakeLists.txt, src/CMakeLists.txt
Add a CMake variable to control this behavior ( default off)
Installs all CXX headers so that a client can bypass C-API limitations
=> Install CXX headers

CMakeLists.txt
Reverts ROCmSoftwarePlatform/MIOpen#215 n- sorry for the thrash, this must be reverted due to unrealized packaging conflicts.
=> Revert "Update CMakeLists.txt: : rocm-opencl-devel to rocm-opencl-dev for RPM Requires"

CMakeLists.txt, Jenkinsfile, src/binary_cache.cpp, src/include/miopen/binary_cache.hpp, src/include/miopen/load_file.hpp, src/include/miopen/solver.hpp, src/load_file.cpp, src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp, src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp, src/solver/conv_ocl_dir2D_bwdWrW_53.cpp, test/CMakeLists.txt, test/ctc.cpp, test/lstm_common.hpp, test/rnn_vanilla_common.hpp, test/soft_max.cpp, test/sqlite_perfdb.cpp
Thix PR contains several changes. ___PLEASE DO NOT SQUASH COMMITS WHEN MERGING.___ Also I recommend reviewing each commit individually.
- ___Fixes:___
- adf4fdb Fixes file-based binary cache, https://github.com/AMDComputeLibraries/MLOpen/issues/2450
- 1ff1a09 Tidy fix that is required after merging of #167 but missing in #212.
- 167a6da1 Permanent workaround for ConvOclBwdWrW53 (NaN on gfx908)
- ___Workarounds:___
- 0335a64 Switches to using the file-based binary cache by default.
- This should resolve this https://github.com/ROCmSoftwarePlatform/MIOpen/issues/226#issuecomment-633659969
- a019ef7 [test_sqlite_perfdb] Reduce amount of work.
- 8ea95121 Disabled `ConvHipImplicitGemmV4R4GenXdlopsWrWFp32`. Reworked special case in `ConvHipImplicitGemmV4R4GenWrWXdlops::IsApplicable()`. 
- …
=> Fix Jenkins issue

src/include/miopen/solver.hpp, src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
Missing `const` in a new solver originated from #205
=> Tidy fix in ConvHipImplicitGemmV4R4WrW

src/solver/conv_multipass_wino3x3WrW.cpp
MultipassWinogradWrW3x{4,5,6} disabled by default for fp16 with stride=1 on gfx908
=> MPWinogradWRW solver update

src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp
v4r4 wrw use for backward weights, not for backward data
=> prevent v4r4 wrw use for backward data

src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp
- Fixed the failure (static_assert) that original v4r4_gen kernels are incompatible with the stride > 1 optimization  (PR #192)
- Disabled the optimization in original v4r4_gen kernels/solvers
- Will add the optimization back in refactored solver/kernel PRs
=> [Hotfix] Disable stride > 1 optimization for v4r4_gen solver

src/ocl/convolutionocl.cpp
By default immediate mode uses GEMM as the fallback method if no known kernel exists for a config. This env variable makes it possible to disable the fallback by exporting:
```bash
export MIOPEN_DEBUG_CONV_IMMED_FALLBACK=0
```
When there is no entry in the find-db for a config and the above env variable is set the convolution will fail and GEMM will not be executed. 
This would be useful for testing #262
=> Add env var to disable immed mode fallback

src/solver/conv_multipass_wino3x3WrW.cpp
MultipassWinogradWrW3x{4,5,6} disabled by default for fp16 n gfx906
=> MPWinogradWRW solver update  gfx906

CMakeLists.txt, src/binary_cache.cpp, src/include/miopen/binary_cache.hpp
- Revert workaround introduced in #240,  0335a64 "Switch to using the file-based binary cache by default. "
- Fix: Do not remove kernels from cache when it is disabled.
- [tests] Fix build of `test_cache`.
=> Re-enable SQLite binary cache

src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_gnchw_gkcyx_gnkhw_lds_double_buffer.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_implicit_gemm_v4r4_gen_xdlops_nchw_kcyx_nkhw_lds_double_buffer.hpp
- the static_assert, which is out of date, causes couples of compiling failures
- remove the static_assert from v4r4_gen kernels
=> Igemm Remove old static_assert from v4r4_gen kernel

src/comgr.cpp, src/hipoc/hipoc_program.cpp, src/include/miopen/comgr.hpp, src/include/miopen/kernel.hpp, src/include/miopen/stringutils.hpp, src/kernels/kernel_includes.cpp.in, test/handle_test.cpp
- Two paths: "in-process" and one-step "COMPILE_SOURCE_TO_FATBIN".
- The latter is experimental and doesn't work for now
- Can be enabled by `MIOPEN_DEBUG_COMGR_HIP_BUILD_FATBIN`.
- Added .hpp/.h includes to the input dataset.
- Build options: `HIP_COMPILER_FLAGS` transformed and added.
- Added env var `MIOPEN_DEBUG_COMGR_COMPILER_OPTIONS_INSERT` for debugging.
- Some refactors.
Some details about performance: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/289#issuecomment-645494178
=> [comgr] HIP support

src/readonlyramdb.cpp
The issue may lead to UB when loading the read-only cache of the system-find-db in the multi-threaded apps. MP (multi-process) applications are not affected.
=> Fix readonlyramdb MT issue

src/comgr.cpp, src/hipoc/hipoc_program.cpp, src/include/miopen/comgr.hpp
- Added support for assembling kernels via comgr.
- Added support for binary kernels.
- Finally disabled spare build path (via temp file) when comgr is used.
- Refactored workaround for the comgr MT issue.
No correctness problems. No GPU time and Wall time regressions. Some (~1.8X) Aux Wall time improvements. Logs & csv files can be provided by request.
=> [comgr] Build ASM kernels

driver/conv_driver.hpp
The main purpose of this is fixing of multiple verification errors in the MIOpenDriver, which is essential for testing.
- Decreased default FP16 tolerance from 7e-2 to 8.2e-3.
- Decreased default BF16 tolerance from 7e-2 to 6.56e-2.
- Doubled tolerance for all WrW convolutions.
- Algorithm-specific adjustments:
- FP32/FP16/BF16 Fwd/Bwd iGemm: allow 10 times bigger deviation.
- FP32 WrW iGemm and Winograd: allow 10 times bigger deviation.
- FP16 WrW iGemm: allow 5 times bigger deviation.
- FP32 WrW iGemm, added workaround for https://github.com/AMDComputeLibraries/MLOpen/issues/2176
- Printed tolerance after verification failure.
- Some refactors (useful by-products of experimental changes).
=> [driver] Verification fixes

src/convolution.cpp, src/find_controls.cpp, src/include/miopen/find_controls.hpp, src/ocl/convolutionocl.cpp
This is continuation of #178, the PR promised by @daniellowell:
> We have just merged in the Hybrid mode as default PR. This means that MIOPEN_FIND_MODE=3 by default.
One thing we overlooked is that the MIOPEN_FIND_ENFORCE=2/3/4 is blocked by hybrid and fast find modes. Artem will open a PR to make it so that if MIOPEN_FIND_ENFORCE > 1 then it will drop MIOPEN_FIND_MODE to NORMAL(1). This will make it behave as normal.
>
>Until that PR is merged make sure you set MIOPEN_FIND_MODE=1 if you are attempting to tune MIOpen off of our current develop branch.
Please note that NORMAL Find mode cannot be enforced in the same way when full search is activated by means of the `exhaustiveSearch` parameter `Find()`:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/da79ca10acb669fd745f5fa65bb24735c54 …
=> Activate NORMAL Find mode when auto-tuning is ENFORCEd

src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp
fix issue #330 
v1r1 bwd 3d FP16/BF16 can't use now until using v2 gridwise to implement it
=> [igemm]prevent v1r1 bwd 3d fp16 until we use v2 gridwise

src/solver/conv_asm_1x1u.cpp, src/solver/conv_asm_1x1u_stride2.cpp, src/solver/conv_asm_3x3u.cpp, src/solver/conv_asm_5x10u2v2b1.cpp, src/solver/conv_asm_5x10u2v2f1.cpp, src/solver/conv_asm_7x7c3h224w224k64u2v2p3q3f1.cpp, src/solver/conv_asm_dir_BwdWrW1x1.cpp, src/solver/conv_asm_dir_BwdWrW3x3.cpp, src/solver/conv_ocl_dir2D11x11.cpp, src/solver/conv_ocl_dir2D3x3.cpp, src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp, src/solver/conv_ocl_dir2D_bwdWrW_53.cpp, src/solver/conv_ocl_dir2Dfwd.cpp, src/solver/conv_ocl_dir2Dfwd1x1.cpp, src/solver/conv_ocl_dir2Dfwdgen.cpp
Resolves ASM & OCL leftovers of #142.
Disables configs that have asymmetric padding in all Solvers that do not anticipate it. See https://github.com/ROCmSoftwarePlatform/MIOpen/issues/142#issuecomment-625941366 for details. 
Note that currently asymmetric padding is possible only for even filter sizes. However this PR affects Solvers that support odd filters as well. This is done in order to avoid adding new implicit dependencies (on how we define “asymmetric padding”).
=> Prevent UB in all ASM & OCL kernels that do not anticipate asymmetric padding

Jenkinsfile, test/CMakeLists.txt
- Improves stability of COMGR tests on Jenkins by lowering parallelism (the suspect of instability is HIP runtime).
- Note: This was prototyped in the [ci-testing-comgr-fix-2](https://github.com/ROCmSoftwarePlatform/MIOpen/tree/ci-testing-comgr-fix-2) branch.
- By-product: Accelerates all Fast tests by replacing Dynamic iGemm tests (>1000 sec which is ridiculous for Fast stages) with their smaller/faster subset (< 10 sec).
=> [CI Fast test stages] Improve stabitility of COMGR tests. Accelerate Dynamic iGemm tests.

src/solver/conv_ocl_dir2D_bwdWrW_53.cpp
Resolves #353 
The IsApplicable method of ConvOclBwdWrW53 does not check the direction of the context and within the IsApplicable method calls the GetSolution method, which throws an exception if the convolution direction is not acceptable.
Ideally, the IsApplicable method should check the direction of convolution and return false instead of throwing an exception.
=> add direction check to ConvOclBwdWrW53  IsApplicable

src/conv/invokers/impl_gemm.cpp
@asroy If we skip settensor, it causes nan in resnext50 as reported by @sunway513 . So, putting it back.
@asroy The assumption we had here in #305 https://github.com/ROCmSoftwarePlatform/MIOpen/pull/305#discussion_r455157461 seemed wrong, causing this nan.
=> Fix nan issue in bwd v1r1 kernel

src/pooling.cpp
=> set default workspaceIndexMode to image index for 3D pooling

src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp, src/kernels/composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_fp16_bfp16.hpp, src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp, src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm_inline_asm.hpp, src/kernels/composable_kernel/include/utility/amd_xdlops.hpp, src/kernels/composable_kernel/include/utility/amd_xdlops_inline_asm.hpp, src/kernels/composable_kernel/include/utility/common_header.hpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/implicitgemm_util.hpp
- Moved M/NRepeats inside XdlopsGemm to avoid redundant data loads
- Added M/NRepeats support into xdlops inline asm (do not support 128x128 due to failed allocation of 256 acc_reg)
- Added more M/N gemm size with repeats, such as `128*32/32*128`, `16*128/128*16`, ...
- Separated inline asm and llvm intrinsic
=> Refactored XdlopsGemm for M/N Repeats

src/ocl/convolutionocl.cpp
- Fixed a bug in GetWorkspaceSize that multiples group_conv twice inside and outside of BackwardDataGetWorkSpaceSizeGEMM (issue #381)
=> [Fix] workspace size calc of gemm for group_conv

src/kernels/composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp, src/kernels/composable_kernel/include/utility/config.hpp
- Workaround performance regression issue (Issue #377 ) due to AccVgpr allocation issue (SWDEV_241664)
- Moving M/N repeats from xdlops gemm to blockwise gemm
=> Workaround performance regression for M/N repeats in xdlops-gemm 

src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops.cpp, src/solver/implicitgemm_util.hpp
=> Workaround for the failure of ConvHipImplicitGemmV4R4GenWrWXdlops

src/hip/hip_build_utils.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/implicitgemm_util.hpp
MIOpen is using "-amdgpu-enable-global-sgpr-addr" option for hip-clang compiler, but the feature has not been correctly implemented in compiler, and can cause GPU core dump in some cases (http://ontrack-internal.amd.com/browse/SWDEV-239555). Currently there is a workaround in MIOpen to prevent this failure. This PR remove this compiler flag and the workaround.
However, disabling the option can result in more than 20% regression in gfx908 fp16 cases.
http://ontrack-internal.amd.com/browse/SWDEV-239555?focusedCommentId=6260190&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6260190
A JIRA is opened to request proper implementation of SGPR offset for global addressing in compiler, so performance can be restored. …
=> Disable faulty compiler option for global addressing using SGPR

src/kernels/MIOpenBatchNormFwdInferPerAct.cl, src/kernels/MIOpenBatchNormFwdInferSpatial.cl, src/kernels/batchnorm_functions.h, src/kernels/reduction_functions.h, src/ocl/batchnormocl.cpp
This PR is specifically for inference. Low batch sizes do better than what we had previously, high batch sizes do worse.
Since this is for inference I suspect for now we don't have to worry a lot for larger batch sizes. 
Data collected on a MI50.
Batch size 1:
  | spatial PR | spatial dev | runtime ratio | per act PR | per act dev | runtime ratio
-- | -- | -- | -- | -- | -- | --
./bin/MIOpenDriver bnorm -i 10 -t 1 -w 1 -V 0 -n 1 -c 1024 -H 14 -W 14   -m ${1} --forw 2 -s 1 -r 1 | 0.010 | 0.013 | 74% | 0.015 | 0.021 | 69%
./bin/MIOpenDriver bnorm -i 10 -t 1 -w 1 -V 0 -n 1 -c 128 -H 28 -W 28   -m ${1} --forw 2 -s 1 -r 1 | 0.011 | 0.009 | 132% | 0.008 | 0.012 | 66%
./bin/MIOpenDriver bnorm -i 10 -t 1 -w 1 -V 0 -n 1 -c 2048 -H 7 -W 7   -m ${1} --forw 2 -s 1 -r 1 | 0.011 | 0.009 | 115% | 0.014 …
=> Dynamic OpenCL batch normalization inference.

Jenkinsfile, codecov.yml
This measures codecov using the gcc debug stage. We could try to add coverage from the hip backend as well in the future.
Right now, it only shows the coverage for this branch [here](https://codecov.io/gh/ROCmSoftwarePlatform/MIOpen/branch/codecov). Once its merged to develop then it will report back the diff coverage between develop and PRs.
=> Add code coverage reports

src/solver/conv_hip_implicit_gemm_v4r1.cpp
- Fixed failure in issue #437, which is due to incorrect vector load length for weight on the E dimension (i.e, GemmK = NHoWo)
=> Fixed vector load length calculation in the ConvHipImplicitGemmV4R1WrW solver

src/comgr.cpp, src/kernels/composable_kernel/include/utility/config.hpp
Partially implements changes required for SWDEV-249870.
- Contains COMGR related fixes necessary for upcoming ROCm
- HIP PCH (precompiled HIP headers) related functionality implemented and tested with ROCm RC
- However functionality is enabled starting from ROCm 4.0 (in fact, currently ___disabled___)
- In other words, this change is NFC when used with previous ROCm releases.
- ___Future___: Enable when ROCm 3.9.x implementation is available.
- ___Future___: Enable also for non-COMGR HIP build path?
- With enabled HIP PCH, the library shows ~1.5 better HIP compilation time.
- None performance or correctness regressions.
=> [COMGR] Added HIP PCH functionality.

src/comgr.cpp
Continuation/completion of #443.
- Enables PCH usage automatically _if_ HIP provides PCH functionality (_and_ COMGR is able to use it).
- Some logging improvements, including `MIOPEN_DEBUG_COMGR_LOG_SOURCE_NAMES`.
=> [COMGR] Enabled HIP PCH functionality.

src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp
original v1r1 bwd xdlops use v4r4's gemmsize....
fix it
=> [igemm]fix bwd-data-v1r1 bug that call GetGemmSize() of a wrong solver

src/kernels/dynamic_igemm/igemm_v4r1_wrw_dynamic.s, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_004x064.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_016x032.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_032x032.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x016.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x032.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x064.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x128.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_064x256.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_128x032.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_128x064.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_128x128.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_256x032.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_256x064.inc, src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908_256x128.inc
Remove globla_store_dword instruction in dynamic igemm wrw pass, because the instruction does not use 64 bits vaddr any more.
=> remove global_store instructions for dynamic igemm wrw pass

src/include/miopen/hip_build_utils.hpp, src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp, src/kernels/composable_kernel/include/utility/config.hpp, src/kernels/composable_kernel/include/utility/in_memory_operation.hpp, src/solver/conv_hip_implicit_gemm_bwd_data_v1r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_data_v4r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_v4r1.cpp, src/solver/conv_hip_implicit_gemm_v4r4.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_weights_v4r4.cpp, src/solver/implicitgemm_util.hpp
Passing HIP compiler version number to composable kernel, to fix this issue due to change intrinsic function:
http://ontrack-internal.amd.com/browse/SWDEV-255582
The hip-clang version that will have the change in intrinsic is 3.10.20405
=> Passing HIP compiler version to composable kernel

src/mlo_dir_conv.cpp
ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm was missing from solver list during PR merging. Add it back in
=> Add ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm in solver list

src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Enlarge tuning range of ConvHipImplicitGemmWrwV4R4Xdlops to fix failure found during Tuna tuning (Solver is applicable, but tuning range is 0-size)
This PR should not enlarge tuning range for those case where tuning range is already large because  ```PerformanceImplicitGemmWrwV4R4Xdlops::IsFastToBeUsedForTuning``` would skip slow tuning parameters
Testing this config, tuning range increase from 0 to 30
```
bin/MIOpenDriver conv -V 1 -i 1 -$ 0 --conv_stride_w 1 --fil_d 1 --group_count 1 --pad_h 0 -^ 1 --fil_h 1 -F 4 -x 1 --conv_stride_d 1 -q 0 -c 32 -m conv -H 27 --spatial_dim 2 --pad_mode default -k 256 --conv_stride_h 1 -% 0 --dilation_h 1 --in_d 1 -n 16 -W 27 --dilation_w 1 -F 4
```
testing this config, tuning range is unchanged (264).
```
MIOpenDriver convfp16 -F 1 -n 64 -g 1 -k 256 -c …
```
=> Enlarge tuning range of ConvHipImplicitGemmWrwV4R4Xdlops

src/comgr.cpp, src/include/miopen/gcn_asm_utils.hpp, src/kernels/inst_wrappers.inc, src/ocl/gcn_asm_utils.cpp
Fix "Workaround for SWDEV-255735" #505.
- Removed useless xnack option from AmdgcnAssembleQuiet(), that was implemented with bugs.
- Added missing xnack option to comgr.
<details><summary><b><i>Original description</i></b></summary><hr>
- Fixed the macro of v_add/sub_co_u32 that allows v_add_u32 with vcc on gfx9
- Used v_add_u32 with 4 operands on gfx9, but gfx9 should only support 3 operands (
https://llvm.org/docs/AMDGPU/AMDGPUAsmGFX9.html#id19). For some reason, the old assembler (rocm 3.7/3.8) accept it. But it failed with rocm 3.10.
<hr></details>
=> Fix "Workaround for SWDEV-255735" (PR 505)

src/include/miopen/solver.hpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
fix two bug in PerformanceImplicitGemmWrwV4R4Xdlops  class:
1 data_per_thread_copy_gemmn should be limited by GemmNPerBlock(not GemmKPerBlock)  in CalculateGemmBBlockCopyPerformanceParameters function 
2.The name of GemmBThreadCopyMoreGemmKPack should be  GemmBThreadCopyMoreGemmK
=> fix bug about wrw atomic add

src/comgr.cpp, src/hip/hip_build_utils.cpp, src/include/miopen/hip_build_utils.hpp, src/kernels/composable_kernel/include/utility/amd_buffer_addressing.hpp, src/kernels/composable_kernel/include/utility/config.hpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/implicitgemm_util.hpp
Relocate compiler flag for hip version into HipBuild(), so that it's not part of the key for kernel binary cache.
Also refactors some code.
----
This is to resolve the problem mentioned at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/499#issuecomment-707391991.
=> Relocate compiler flag for hip version into HipBuild()

src/solver/conv_asm_dir_BwdWrW3x3.cpp
This fixes cherry-picked #534 in `rocm-3.10.x-staging`
=> [rocm-3.10.x-staging] Fix for: W/A: disable ConvAsmBwdWrW3x3 for stride >= 2 && gfx9

src/comgr.cpp
`-msram-ecc` shouldn't be passed to compiler during OCL builds when device does not support sram-ecc target feature. Otherwise HIP runtime fails to load binary.
=> [COMGR] OCL builds: fix for sram-ecc feature for gfx900

src/include/miopen/solver.hpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp
-  To fix the failure [here](http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/reshuffleAndReduceTestCases/117/pipeline/), which is due to narrowed search space for fast tuning.
- Failed config: ./bin/MIOpenDriver convfp16 -n 1 -c 16 -k 16 -H 28 -W 28 -u 2 -v 2 -l 1 -j 1 -p 3 -q 3 -x 3 -y 3 -F 1
- Add spare, 1) first-round use fast tuning, 2) second-round do full search
- Based on PR #528
=> Add spare in the tuning of V4R5

src/include/miopen/solver.hpp, src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
PR #499 removed a compiler workaround, which has the side effect of reducing the tuning range for some HIP iGEMM solvers, by considering smaller blockwise-GEMM as lower performance, which turns out to be wrong in some cases.  
This PR make solver tuning cover smaller blockwise-GEMM for all iGEMM solvers.
=> Increase tuning range for hip iGEMM

src/comgr.cpp, src/include/miopen/gcn_asm_utils.hpp, src/ocl/gcn_asm_utils.cpp, src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp, src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp, src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
Cherry-picks for `rocm-3.10.x-staging` from:
- #529 [COMGR] OCL builds: fix for sram-ecc feature for gfx900
- #536 [COMGR] Disable unnecesssary assembler detection.
- #538 Added missing checks for new iGemm solvers so they obey the ASM & HIP kernel on/off controls.
These are necessary for embedded builds.
- Radeon VII, ROCm 3.5.
- 93 known FP32 convolution configs
- Baseline vs this PR
- Normal Find mode + Immediate mode, HIP backend
- Normal Find mode, COMgr path
No regressions.
=> [rocm-3.10.x-staging] Important cherry-picks

test/conv_common.hpp
The rule in convolutionocl has been change for GEMM validation check.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/88bd3f7cfe95ddd2c4e953f47320166bd25d96b0/src/ocl/convolutionocl.cpp#L365-L368
Adjust ctest according to new rules for int8 test.
=> revise int8 conv test validation check based on latest conv host

driver/tensor_driver.hpp, src/pooling_api.cpp
- Computations should be performed in `size_t` type.
- 1046ba6 resolves issue #494 (partially, at least)
=> Fix for huge pooling workspace (library) and for huge tensors (driver)

src/include/miopen/gcn_asm_utils.hpp, src/ocl/gcn_asm_utils.cpp
Offline assembler detection fails in embedded environment (and unnecessary for COMGR assembly path). The detection happens at run time. Symptom:
```
MIOpen(HIP): Error [ValidateGcnAssemblerImpl] Wrong path to assembler: '/opt/rocm/llvm/bin/clang'. Expect performance degradation.
```
As a result, all solvers that use ASM kernels will be disabled.
This PR fixes this issue.
=> [COMGR] Disable unnecesssary assembler detection

src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp, src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp, src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp
This is #537 for `develop` + more fixes due to more new solvers. We must keep debugging controls in good shape.
/cc @daniellowell
=> Added missing checks for new iGemm solvers so they obey the ASM & HIP kernel on/off controls.

src/include/miopen/generic_search.hpp
Compiling all kernels at once with Precompile kernels. This enables us to compile in parallel for Tuna.
Ran local tests to get speed for compiling/evaluating separately on MI100.
./build/bin/MIOpenDriver conv -F 2 -n 128 -g 1 -k 1024 -c 1024 -H 35 -W 35 -y 3 -x 3 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -V 0 -w 1 -t 1 -i 1
common env vars:
export MIOPEN_FIND_ENFORCE=4
export MIOPEN_LOG_LEVEL=6
export MIOPEN_DEBUG_CONV_GEMM=0
export MIOPEN_DEBUG_CONV_FFT=0 
export MIOPEN_DEBUG_CONV_DIRECT=0
export MIOPEN_DEBUG_CONV_WINOGRAD=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=1
Regular compile+evaluate at the same time for igemm: 
-- 5 iteration: **avg 282 sec** 
-- 10 iteration: **avg 145 sec**
Separate compile, evaluate using extra env vars for compile:
export MIOPEN_COMPILE_AND_RUN=0
export …
=> Fix for distinct compile/evaluate 

src/solver/conv_MP_bidirectional_winograd.cpp
W/A for SSD convergence issue mentioned in SWDEV-257202 for 3.10 release. Full blown fix to be provided later by @shurale-nkn.
=> [WORKAROUND] All MP Bidirect Winograd Solvers disabled by default.

src/conv/invokers/impl_gemm.cpp, src/include/miopen/solver.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.hpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw.cpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_convolution_backward_weights_implicit_gemm_v4r4_xdlops_nchw_kcyx_nkhw_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_bwd_data_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops_nchw_kcyx_nkhw.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
1. Refactor some of functions for ```ConvHipImplicitGemmWrwV4R4Xdlops``` and ```ConvHipImplicitGemmWrwV4R4Xdlops_Padded_Gemm``` performance parameter calculation
2. Fix performance parameter calculation issues in ```ConvHipImplicitGemmWrwV4R4Xdlops_Padded_Gemm``` that cause several compilation failures in 
http://ontrack-internal.amd.com/browse/SWDEV-258416
http://ontrack-internal.amd.com/browse/SWDEV-257202
```
MIOpenDriver conv -F 4 -n 120 -g 1 -k 340 -c 256 -H  1 -W  1 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -V 1 -w 1 -t 1 -i 1 
MIOpenDriver conv -F 4 -n 120 -c 510 -H 5 -W 5 -k 250 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 1 -t 1
```
3. Fixed bwd-data-v4r1 issue: need to call SetZero for some cases.
=> Fix ConvHipImplicitGemmWrwV4R4Xdlops_Padded_Gemm performance parameter calculation issue

test/sqlite_perfdb.cpp
Currently the test has imperfections that can lead to timeouts under heavy loads. This should reduce the probability of timeouts, especially on systems with slow HDD.
On my system (fast SSD storage):
test | \<blank\> | --all
-- | -- | --
test_perfdb | 1.6 sec | 13 sec 
test_sqlite_perfdb (baseline) | 29 sec | __480 sec__
test_sqlite_perfdb (this PR) | 29 sec | ___114 sec___
=> [tests] Reduce of workload for "test_sqlite_perfdb --all"

test/lstm_common.hpp
The purpose of this PR is to convert non-const lstm cpu verification function to const type in order to help reduce the test time and the robustness of the verification.
Related work: #448
=> refactor lstm cpu verification to const function

src/ocl/convolutionocl.cpp
This fixes https://github.com/ROCmSoftwarePlatform/MIOpen/issues/639
Right after context is created by `auto ctx=...`, there should be a `ctx.SetStream(&handle);` to set stream of the newly created context (fwd/wrw immediate already have this setStream, but not bwd). Otherwise the `stream` member of this context will always be nullptr, and will likely crash in later software flow.
=> Fix potential bwd immediate crash by add missing setStream() call to context

src/hip/handlehip.cpp, src/include/miopen/device_name.hpp, src/ocl/handleocl.cpp
- Trim target features from the device name, e.g. `gfx908:sramecc+:xnack-` -> `gfx908`.
- [Note] This PR is NFC if target features are not reported by runtime.
- Optimize for speed to compensate for additional calculations in `GetDeviceName()`.
=> Workaround for SWDEV-262823

src/include/miopen/convolution.hpp, src/ocl/convolutionocl.cpp
- Catch exceptions internal to FFT solver/solution for better survivability.
- Handle env var outside of `Find()` to simplify code.
This should precede #615
=> [NFC] Unify FFT solver usage

src/include/miopen/conv/problem_description.hpp
Follow up from @atamazov's comments [here](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/343#discussion_r456113882). The alternative condition for `Get<In/Out/Weight>Size()` are wrong, and we are not sure what it actually calculates. Fixing it in case it cause any issues in the future.
-----
Example, say we have NCHW layout, and have N: 128, C: 3 H: 5 W:5, for input size:
- The default condition: N x C x H x W = 128 x 3 x 5 x 5
- The alternate condition: N x CHW x HW x W = 128 x 75 x 25 x 5
=> Follow up to PR#343: Fix problem description Get*Size()

src/include/miopen/convolution.hpp, src/include/miopen/problem_description.hpp, src/include/miopen/solver.hpp, src/ocl/convolutionocl.cpp, src/solver/conv_bin_wino3x3U.cpp, src/solver/conv_winoRxS_f2x3.cpp
Continuation of #424. Implements (30.10) and (20) for WinogradRxS F(2,3) (n_groups=1) from #410.
- Updates the core of the library.
- Expected to allow simpler integration of MLP classifier
- Adds `GetWti()` for 3x3 WinogradRxS F(2,3), all directions.
- Adds very approximate `GetWti()` for GEMM, all directions.
Provides:
- Performance improvements for non-group convolutions, all directions:
- For Immediate Mode Fallback & FAST Find mode (unseen configs)
- Significant FP16 improvements because now we utilize Winograd
:warning: ___For detailed understanding of this code, I recommend reviewing each commit individually.___ Each commit has clear description, so the reviewer has luxury to skip what he or she is not interested in (for ex. refactors).
- Updated machinery that uses `GetWti()` in …
=> Immediate Mode Fallback: Implement & use GetWti for Winograd v21_1_1 and GEMM

driver/conv_driver.hpp
Notice `-S 13` here:
```
$ ./bin/MIOpenDriver conv -S 13 -n 64 -c 256 -H 56 -W 56 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 2 -t 1 -V 0
MIOpenDriver conv -S 13 -n 64 -c 256 -H 56 -W 56 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 2 -t 1 -V 0 
Backward Data Conv solutions available: 4
- id: 55 algo: 5, time: 2.64976 ms, ws: 0, name: ConvHipImplicitGemmBwdDataV1R1
- id: 2 algo: 1, time: 2.6856 ms, ws: 0, name: ConvAsm1x1U
- id: 33 algo: 0, time: 2.80912 ms, ws: 0, name: gemm
- id: 37 algo: 3, time: 5.65664 ms, ws: 0, name: ConvBinWinogradRxSf3x2
Warning: Solution id (13) is not reported by the library. Trying it anyway...
MIOpen Backward Data Conv. Algorithm: -1, Solution: 13/ConvOclDirectFwd1x1
GPU Kernel Time Backward Data Conv. Elapsed: 4.330303 ms (average)
stats: …
```
=> [Driver] Allow arbitrary solver id in `-S`. Support symbolic solver names.

src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp
- When E == EPerBlock, the non-xdlops v4r1 fwd kernel failed on Vega20 (ROCm 3.5/3.7) with scratch memory
- Added a restrict that E (i.e., GemmK) must be multiple of 2 x EPerBlock
=> [iGemm] Workaround a tuning issue of non-xdlops gemm

include/miopen/miopen.h, src/handle_api.cpp, src/include/miopen/generic_search.hpp, src/ocl/convolutionocl.cpp
During compile only perf_db is empty hence we would see "...cannot be executed due to incorrect params" err thrown, but we want to customize this err since its caused by compiling only and we want Tuna to recognize it.
=> Early escape for compile_only + custom err

src/hip/hip_build_utils.cpp
This is by-product of [discussion in SWDEV-268264](http://ontrack-internal.amd.com/browse/SWDEV-268264?focusedCommentId=6818681&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6818681). The immediate goal is getting rid of useless code. Also this gives some boost of HIP builds.
The by-product of this PR is improved compatibility with different compiler versions (only when built with HIP backend). For example, MIOpen is able to work with build 6326 (HIP version 4.0.20491, TargetID is enabled, at least partially) regardless of whether TargetID stuff in MIOpen is enabled or disabled (tested manually).
[Informative] Un-bundling will be also removed from OpenCL BE as soon as [loading bundled program is added to OpenCL …
=> [HIP backend] Remove fat binary unbundling

CMakeLists.txt, include/miopen/config.h.in, src/hip/hip_build_utils.cpp, src/hipoc/hipoc_program.cpp
This resolves issue #684.
Also this PR allows for `cmake ... -DMIOPEN_OVERRIDE_HIP_VERSION_MINOR=1 ...` when building MIOpen. This technique resolves current TargetID and CO V4 issues with mainline compiler & library.
Radeon VII.
| Compiler & libs | HIP version | Backend | Result | Notes
| -- | -- | -- | -- | --
| ROCm 4.0 | 4.0.20496 | HIP | Ok
|  |  | OpenCL | Ok
| Mainline build 6326 | 4.0.20491 | HIP | Ok
|  |  | OpenCL | FAIL | Result is actually Ok but `test_lstm` is failing due to OpenCL kernel build warning: `error: result of comparison of unsigned expression < 0 is always false` for `...(group_id_z < n_work_groups_with_1_more)...` <br><br>***Must be built*** with `-DMIOPEN_OVERRIDE_HIP_VERSION_MINOR=1`, otherwise fails on each OCL progrem load with `Error creating code object …
=> [HOTFIX][TargetID] Unblock MIOpen for ROCm 4.0 and 4.0.1 RC. Possibility for unblock for mainline.

src/solver/conv_MP_bidirectional_winograd.cpp, src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp, src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp, src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_multipass_wino3x3WrW.cpp, src/solver/conv_ocl_dir2D11x11.cpp, src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp, src/solver/conv_ocl_dir2D_bwdWrW_2.cpp, src/solver/conv_ocl_dir2D_bwdWrW_53.cpp, src/solver/conv_ocl_dir2Dfwd.cpp, src/solver/conv_ocl_dir2Dfwd1x1.cpp, src/solver/conv_ocl_dir2Dfwdgen.cpp, src/solver/conv_winoRxS_f3x2.cpp, src/solver/fft.cpp
All existing kernels are NCHW only. I'm adding this filter just so that when NHWC kernels are added, MIOpen won't get confused and return a kernel with wrong layout support.
=> Adding applicable filter to consider layout to existing kernels

src/exec_utils.cpp, src/hipoc/hipoc_program.cpp, src/include/miopen/conv/context.hpp, src/include/miopen/generic_search.hpp, src/solver/conv_asm_1x1u_bias_activ.cpp, test/CMakeLists.txt
Fixes #683.
The issue was caused by generic search-related parameters being passed to the solution even when its purpose was not tuning.
Note that auto-tuning of this Solver still fails due to some other issue, see:
- https://github.com/ROCmSoftwarePlatform/MIOpen/issues/560#issuecomment-763985085.
- https://github.com/ROCmSoftwarePlatform/MIOpen/pull/533#discussion_r520911050
=> Fixed invalid compilation params for fused ConvBiasActivAsm1x1U

src/reducetensor.cpp
Disable  CK_USE_AMD_BUFFER_ADDRESSING when compiling Generic-Reduction kernels on gfx1030
EDIT by @atamazov: Workaround for #557
=> Disable the using of llvm instrinsic for Generic-Reduction Kernels on gfx1030

Jenkinsfile, src/fusion.cpp, src/md_graph.cpp, src/ocl/convolutionocl.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
- Fixed: "failed" at Info logging level leads to false CI failures (as tests assume "failed" is indication of a failure).
- Fixed: The default log level was incorrectly used instead of level 5 at stages "Hip Debug COMGR" and "Hip Debug Embedded Vega20".
- Improved readability of logs. Whenever some detailed log level are used (5 or more), `--verbose` added to the tests.
All these are important for triaging/debugging complicated PRs, like @DrizztDoUrden's #473, so high priority & value.
=> [CI] Improved error logs. Eliminated some false failures.

src/CMakeLists.txt, src/hip/handlehip.cpp, src/include/miopen/ocldeviceinfo.hpp, src/include/miopen/rocm_features.hpp, src/ocl/clhelper.cpp, src/ocl/handleocl.cpp, src/target_properties.cpp
- Added logging of raw device name.
- Introduced the 'rocm_features' module.
- Formalized W/A for issue 1711.
- Removed useless workaround macro
- Used gcnArchName instead of gcnArch since ROCm 4.0
=> [HIP BE] Use hipDeviceProp_t.gcnArchName instead of gcnArch

Jenkinsfile
The gfx803 nodes are malfunction often. This blocks CI testing. We are gong to retire those nodes. 
https://github.com/AMDComputeLibraries/MLOpen/issues/1934 updated.
=> [CI] Dismiss Fiji from CI testing.

include/miopen/miopen.h, src/comgr.cpp, src/include/miopen/mlo_internal.hpp
- OCL BE: Fixed ROCm 4.0 build warnings like "CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220"
- COMGR: Use "-cl-std=CL1.2", just like in other build paths.
=> [OCL BE] Fix ROCM 4.0 build warnings. [COMGR] Use OpenCL 1.2

src/ocl/batchnormocl.cpp
This is a temporary workaround fix to disable batchnorm backward code.
=> Batchnorm fix for disabling ASM code

src/db_record.cpp
Let's move the first three lines (`SetValues`) down from log level 5 to log level 6:
```
MIOpen(HIP): Info [SetValues] , content inserted: ConvAsm1x1U:2,8,4,16,1,4,4,1
MIOpen(HIP): Info [SetValues] , content inserted: ConvOclDirectFwd1x1:1,128,1,1,0,1,4,4,0
MIOpen(HIP): Info [SetValues] , content inserted: ConvBinWinogradRxSf2x3:46
MIOpen(HIP): Info [GetValues] =ConvAsm1x1U:2,8,4,16,1,4,4,1
```
=> [NFC][SQLite perf-db] Less spam at log level 5

CMakeLists.txt
Resolves issue #666.
The logic or removal of internal llvm options has been introduced in HIP in https://github.com/ROCm-Developer-Tools/HIP/pull/2035#issuecomment-616861118. Relevant support in MIOpen was added at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/165/files#r571645949, but then has been removed in #190 by mistake. This PR restores it and adds necessary comments to avoid removal by mistake in the future.
Tested with:
```
export MIOPEN_DEBUG_CONV_FFT=0
export MIOPEN_DEBUG_CONV_GEMM=0
export MIOPEN_DEBUG_GCN_ASM_KERNELS=0
export MIOPEN_DEBUG_OPENCL_CONVOLUTIONS=0
```
___Average FP32 performance gain: 3.5X___
=> [OCL BE] Fix: Restore llvm-specific HIP build options to reclaim GPU performance.

src/kernels/MIOpenBatchNormBwdPerAct.cl, src/kernels/MIOpenBatchNormFwdTrainPerAct.cl, src/ocl/batchnormocl.cpp, test/bn_peract_test.cpp
~~This comes from this issue. Should stabilize the calculation:
http://ontrack-internal.amd.com/browse/SWDEV-253606~~
Turns out not to be the issue. Still though calculations are not stable in our tests.
=> [BN] Update kernel to stabilize variance calculation.

src/include/miopen/find_solution.hpp, src/include/miopen/logger.hpp
This is 4.1.x specific hack to resolve SWDEV-270790. Should not be back-propagated to develop, staging or mainline.
=> [HOTFIX][4.1.x] Lower logging level from Warning to Info for incorrect PerfConfigs loaded from db

src/kernels/conv3x3.s
Fixed assembly error in ROCm >= 4.1, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/665/files#r549486324 for more info.
=> [HOTFIX] Do not reserve xnack mask SGPR in the 3x3 asm kernel.

src/kernels/Conv_Winograd_v21_1_2_metadata.inc
This PR fixes Conv_Winograd_v21_1_2 hangs on the gfx10 caused by missing _.amdhsa_wavefront_size32_ directive (due to incorrectly allocated amount of VGPR).
For more information refer to SWDEV-269929
⚠️ _.amdhsa_wavefront_size32_ directive is only available for gfx10+
* gfx1030 ROCm 4.0, gfx906 ROCm 4.0
* fp16, fp32
=> Add missing amdhsa directive for Conv_Winograd_v21_1_2 metadata

Jenkinsfile, test/CMakeLists.txt
- [Optimization] Even if stage is intended to run only on Vega10 node, build docker image as if it is intended to run on any Vega GPU.
- Currently things like `gpu_arch: gfx900` are used with "standard" image names. This leads to many useless image rebuilds.
- [Optimization] Same for Vega20 stages
- [Optimization] [Fix] Use `miopen-hip-clang` as a basename for hip-clang based docker image.
-  Note: Currently Jenkinsfile uses `miopen` which is actually intended for hcc-based dockers. This issue was introduced in #759
- [Optimization] Use the same image name for `HipNoGPU` -- it actually uses the same image
- [Optimization] Use different images names for MIOpenTensile "latest" docker image
- Currently we use "standard" name and that leads to useless image rebuilds per each job.
- …
=> [CI] Select image names and docker build args to get rid of useless image rebuilds. [tests][FP16][MI100] Remove useless tests.

Jenkinsfile, test/CMakeLists.txt
This resolves issue described at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/139/files#r578672245. This is expected to speed up CI testing. Also some other edits for clarity.
=> [tests] Remove useless tests from low-precision stages.

src/kernel_cache.cpp
The reason of the issue: https://github.com/AMDComputeLibraries/MLOpen/pull/2400/files#r572106557. Unlike `AddProgram` and `AddKernel`, `HasProgram` does not use the `ProcessParams` trick, that adds a space to the compile args. That is why `HasProgram` fails to find existing program, if it has been added by `AddProgram` or `AddKernel`. Consequently, `PrecompileSolutions` rebuilds programs that already reside in the binary cache.
However we do not need `ProcessParams` at all, because currently -cl-std is appended to the end or params ([see comment in `ProcessParams`](https://github.com/AMDComputeLibraries/MLOpen/commit/2358609cfcc3d6d84245d89636b61b5b14d8d733#r46885082) that explains why it is required).
=> Remove outdated (and now wrong & harmful) workaround for apple

src/solver/conv_ocl_dir2Dfwd1x1.cpp
- Due to the compiler issue SWDEV-271887, MIOpenConv1x1J1 gets compilation failure on Navi21
- Disabled MIOpenConv1x1J1 on Navi21 until the compiler fix merged
=> [Workaround] Disable MIOpenConv1x1J1 on Gfx10

test/handle_test.cpp
- Fixed test_handle_test failure on gfx1030 due to unknown arch
- Added gfx1030 into the known_arch list
=> [Fix] test_handle_test failure on gfx1030

src/hip/hip_build_utils.cpp
#786 cherry-picked for develop (cherry picked from commit 0c27e45c20c18a620d08422347c59f3096c12f81). Should resolve http://ontrack-internal.amd.com/browse/SWDEV-274497.
UPDATE: includes additional check that prevents failures with 4.2 before patch 21072.
=> [OCL BE][HIP] Use "hipv4" for unbundler in 4.1 and in 4.2 starting from 21072.

src/include/miopen/rocm_features.hpp, src/include/miopen/solver.hpp, src/ocl/convolutionocl.cpp, src/solver/conv_direct_naive_conv_bwd.cpp, src/solver/conv_direct_naive_conv_fwd.cpp, src/solver/conv_direct_naive_conv_wrw.cpp
This PR is intended for 4.1 release only. Related ticket: http://ontrack-internal.amd.com/browse/SWDEV-276757
W/A for MIOpenGEMM issues with ROCm 4.1. The exact reason is not known yet, the most likely reason is a bug in MIOpenGEMM. Note that MIOpenGEMM is used only for OCL BE and is deprecated. It is also possible that the reason is an issue in the OpenCL compiler, but I do not see any problems with other OpenCL kernels.
Some failing cases:
```
test_immed_conv2d --float --cmode conv --pmode default --group-count 1 --input 1, 3, 224, 224 --weights 1, 3, 11, 11 --pads_strides_dilations 1 1 1 1 1 1 --trans_output_pads 0 0
test_immed_conv2d --float --cmode conv --pmode default --group-count 1 --input 1, 3, 224, 224 --weights 1, 3, 7, 7 --pads_strides_dilations 3 3 2 2 1 1 --trans_output_pads …
```
=> [rocm-4.1.x][HOTFIX][WORKAROUND][OCL] Disable MIOpenGEMM for failing configs. Backup GEMM with Naive Direct Solvers for Immediate Fallback.

src/CMakeLists.txt, src/kernels/kernel.cpp.in, src/kernels/kernel_includes.cpp.in
- Removes huge generated kernel headers from tidy checks. On current develop, `make tidy` progressed from ~40 minutes to 15 mins. Without this, #680 takes >5 hours to complete.
- Moves builds of generated kernel sources to the beginning of `MIOpen_source`. This saves ~1 minute during library build.
=> [CI] Remove huge generated kernel headers from tidy checks. Accelerate parallel library builds.

src/hip/hip_build_utils.cpp
Each time when HIP kernel is being compiled, the library writes to disk all include files. The total size of this with #680 is ~81MB. ~80 MB of those are assembly `.inc` files, which are irrelevant. This affects performance. HDD write speed on my machine:
```bash
$ sudo dd if=/dev/zero of=/mnt/hdd/dd-test bs=330k count=25000
25000+0 records in
25000+0 records out
8448000000 bytes (8.4 GB, 7.9 GiB) copied, 58.5778 s, 144 MB/s
```
Which means that 80MB of useless files adds ~0.55 sec at least.
This PR writes to disk only HIP headers thus reducing to total size down to ~1MB.
=> [HIP build] Do not write unnecessary files to disk.

Jenkinsfile
We should always clean `./install` directory. Leftowers after failed/terminated tests are not just unwanted but also lead to clang-format failures.
Also resolves: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/806#discussion_r598148074
=> [CI] Fix & refactor build/install directory handling.

src/comgr.cpp, src/hipoc/hipoc_program.cpp, src/include/miopen/gcn_asm_utils.hpp, src/include/miopen/hip_build_utils.hpp, src/include/miopen/target_properties.hpp, src/ocl/clhelper.cpp, src/ocl/gcn_asm_utils.cpp, src/target_properties.cpp
This should fix http://ontrack-internal.amd.com/browse/SWDEV-278900 and unblock mainline. The problem is caused by recent changes in the compiler. Now the compiler does not allow you to disable features that do not exist on the target device.
For example, if a target does not have the XNACK feature (like Navi 21), then you can't explicitly tell the compiler to not generate extra code for XNACK. The compiler is smarter than you, it decides itself and beat your a** if you try to suggest it to do the same.
=> [Nv21][HOTFIX][TargetId] Support features disabled on target (SWDEV-278900)

src/include/miopen/rocm_features.hpp, src/include/miopen/solver.hpp, src/ocl/convolutionocl.cpp
This is basically a replica of #798 cherry-picked for `rocm-4.2.x-staging`. The MIopenGEMM issue with the ROCm 4.1 compiler did not go away when using the ROCm 4.2 compiler. More info at #798.
I plan to create similar PR for `develop`.
=> [rocm-4.2.x][HOTFIX][WORKAROUND][OCL] Disable MIOpenGEMM for failing configs. Backup GEMM with Naive Direct Solvers for Immediate Fallback.

src/solver/gemm.cpp, src/solver/gemm_bwd.cpp
Fixes issue #846.
Blocker for Mainline update. The faulty code is now in Staging, and we should not promote it to Mainline until this fix is arrived to Staging.
=> Fix issue 846 - Make GEMM Fwd/Bwd solvers non-applicable when MAX_MEM_ALLOC_SZ exceeded

Jenkinsfile
- Removes definition of `MIOPEN_DEBUG_IMPLICIT_GEMM_NON_XDLOPS_INLINE_ASM` that is originated from https://github.com/AMDComputeLibraries/MLOpen/pull/2491. Not needed anymore (and harmful -- the library should decide about this automatically).
- W/A for #853.
=> [Jenkinsfile] Don't disable inline asm for non-XDLOPs targets. Disable Codecov.

src/include/miopen/rocm_features.hpp, src/include/miopen/solver.hpp, src/ocl/convolutionocl.cpp, src/solver/gemm.cpp
Fixes #845. This is basically a replica of #798 backported to `develop`.
=> [WORKAROUND][OCL] Disable MIOpenGEMM for failing configs.

src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp
- Fixed the reg allocation issue for K-reduction in xdlops gemm, which allocates more registers than it needs
- Refactored code to improve the readability of code
=> Fixed reg allocation for k-reduction in xdlops gemm

src/binary_cache.cpp, src/include/miopen/sqlite_db.hpp, src/sqlite_db.cpp
* handle missing embedded files
* Why: When an embedded file is not found in the internal map, instead of throwing an exception, MIOpen marks the database as invalid effectively converting accesses to that database as No-Op.
* remove file IO when embedded
* See also [this comment](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/878#issuecomment-825089011).
This PR addresses [SWDEV-282133](http://ontrack-internal.amd.com/browse/SWDEV-282133)
=> Handle missing file when embedded build of MIOpen (SWDEV-282133)

src/CMakeLists.txt, src/conv/invokers/mlir_impl_gemm.cpp, src/include/miopen/conv/invokers/mlir_impl_gemm.hpp, src/include/miopen/solver.hpp, src/mlo_dir_conv.cpp, src/solver.cpp, src/solver/conv_hip_implicit_gemm_mlir_bin_bwd.cpp, src/solver/conv_hip_implicit_gemm_mlir_bin_fwd.cpp
Refer to #841 for the previous step in the series.
I did the following in this PR:
- Implemented the MLIR binary backend invoker, bwd path
- Implemented the MLIR binary backend solver, bwd path
I will work through the remaining work incrementally: This help to reduce the complexity for both myself as developer and the reviewers.
I did not add unit test for mlir binary backend because the corresponding commit does not guarantee correctness for bwd path. This means that I will rework this solver/invoker once I am able to bump the MLIR commit who can guarantee it.
=> Implement mlir binary backend - step 2: bwd path

src/comgr.cpp
=> [COMGR] Fix UB: reference binding to null pointer of type 'char'

src/include/miopen/solver.hpp, src/ocl/convolutionocl.cpp, src/solver/gemm.cpp, src/solver/gemm_bwd.cpp
- Resolves #890
- @DrizztDoUrden Please take in to account this when implementing WrW GEMM Invokers.
- From now on, Naive Direct always backs up GEMM on Immediate Mode Fallback path.
=> [OCL][FP16] Fix: Disable GEMM/MIOpenGEMM. [Immediate Mode] Always use Naive Direct in Fallback.

src/CMakeLists.txt, src/conv/invokers/mlir_impl_gemm.cpp, src/include/miopen/conv/invokers/mlir_impl_gemm.hpp, src/include/miopen/solver.hpp, src/mlo_dir_conv.cpp, src/solver.cpp, src/solver/conv_hip_implicit_gemm_mlir_bin_wrw.cpp, test/CMakeLists.txt
Refer to #841 and  #889 for the previous step in the series.
I did the following in this PR:
- Implemented the MLIR binary backend invoker, wrw path
- Implemented the MLIR binary backend solver, wrw path
- ctest coverage for wrw path
I will work through the remaining work incrementally: This help to reduce the complexity for both myself as developer and the reviewers.
=> Imlement mlir binary backend - step 3: wrw path

src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp
#834 contains a typo. The issue regularly appears during testing of #852. This is urgent or our CI will be red soon.
=> [HOTFIX][CI][ROCm 3.7] Fix typo in PR 834

src/hipoc/hipoc_program.cpp, src/include/miopen/kernel_warnings.hpp, src/kernel_warnings.cpp, src/ocl/clhelper.cpp
Resolves http://ontrack-internal.amd.com/browse/SWDEV-270602 and some other OpenCL build errors that happen with ROCm 4.2 when `BUILD_DEV=On`.
=> [NFC][ROCm 4.2] Workarounds for OpenCL build errors in DEV builds (SWDEV-270602)

src/CMakeLists.txt, src/conv/invokers/mlir_impl_gemm.cpp
From #908 
I compared this case and the `mlir_build.h` case, I honestly don't see a reason why compiler want to compile this cpp file (therefore the need to find the dependent `Miir.h`). When `MIOPEN_USE_MLIR` is not turned on, the compiler should not have visibility into any of the `mlir_impl_gemm.hpp` header functions.
However, it is what it is. Adding a macro to make sure when compiler does compile this implementation file, it does not require the `Miir.h` header.
=> [HOTFIX] Fix build error due to missing `Miir.h` when MIOPEN_USE_MLIR=0 and MLIR library is not available

driver/miopen_Reduction.hpp, driver/reduce_driver.hpp, src/reducetensor.cpp, test/reduce_test.cpp
Previous implementation of miopenReduceTensor() assumes alpha/beta has the same data type as the input tensor.  This change assumes/interprets alpha/beta has float type.  The miopenReduceTensor() API does not change.  
<details><summary><b><i>The change has gone through the following tests:</i></b></summary>
Regular MIOpen tests:
```bash
$ ./bin/test_reduce_test --all --float
$ ./bin/test_reduce_test --all --half
```
Manual testing:
```bash
#!/bin/bash
bin/MIOpenDriver reduce -D 64,3,280,81  -R 0 -O 2 -N 0 -I 1
bin/MIOpenDriver reduce -D 64,3,280,81  -R 0 -O 3 -N 0 -I 1
bin/MIOpenDriver reduce -D 64,3,280,81  -R 0 -O 4 -N 0 -I 1
##
bin/MIOpenDriver reduce -D 64,3,280,81  -R 1 -O 2 -N 0 -I 1
bin/MIOpenDriver reduce -D 64,3,280,81  -R 1 -O 3 -N 0 -I 1
bin/MIOpenDriver reduce -D 64,3,280,81 …
```
=> Use FP32 scaling factors in ReduceTensor, regardless of the tensor data type (SWDEV-284921).

Jenkinsfile
Some recent Jenkinsfile improvements (mainly, node selection updates) must be merged into `rocm-4.2.x`. This is necessary to enable testing of `rocm-4.2.x` on our CI. This change is NFC for CQE and users.
=> [CI][rocm-4.2.x] Unblock our CI for rocm-4.2.x branch

Jenkinsfile, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
Some failing configs:
```
./bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 1, 320, 28, 28 --weights 1, 320, 1, 1 --pads_strides_dilations 1 1 1 1 1 1 --trans_output_pads 0 0 
./bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 1, 32, 14, 14 --weights 1, 32, 5, 5 --pads_strides_dilations 2 2 1 1 1 1 --trans_output_pads 0 0 
./bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 1, 32, 16, 16 --weights 1, 32, 5, 5 --pads_strides_dilations 1 1 1 1 1 1 --trans_output_pads 0 0 
```
<details><summary><b><i>Example failing log:</i></b></summary>
```
2021-05-10T01:06:38.937Z] /home/jenkins/workspace/MLLibs_MIOpen_swdev-2848484/build/bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 …
```
=> [CI][rocm-4.2.x][BF16] Disable V4R4 padded_gemm Solvers for BF16 with ROCm 3.7 due to fatal HIP compiler errors.

src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp
This is replica of #920 for develop. Necessary to unblock our CI, which uses ROCm 3.7 right now and fails for time to time.
The follow-up issue is #928.
=> [WORKAROUND][MI100][BF16] Disable V4R4 padded_gemm Solvers for BF16 with ROCm 3.7 due to fatal HIP compiler errors.

driver/InputFlags.cpp, driver/InputFlags.hpp, driver/conv_driver.hpp
After https://github.com/ROCmSoftwarePlatform/MIOpen/pull/343, if user try MIOpenDriver with 3d convolution, it must specify the `in_layout`, `fil_layout`, `out_layout`, explicitly, otherwise it will use the default layout as `NCHW` (2d layout) while[ initialize cmd line arg](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/driver/conv_driver.hpp#L570), and result in fail.
More over, if enable `MIOPEN_ENABLE_LOGGING_CMD` and dump a 3d conv, it will not log the `in_layout`, `fil_layout`, `out_layout` if current layout is default (NCDHW). So to unify the behavior with 2d conv, this PR fix this problem by providing a default value(NCDHW) for 3d convolution in MIOpenDriver.
e.g:
A 3d conv config as below:
`./bin/MIOpenDriver conv  -n 2 -c 2 --in_d 5 -H 4 -W 3 -k 3 --fil_d 5 -y 4 -x …
=> [MIOpenDriver] 3d conv set default layout as NCDHW

src/kernels/conv5x10u2v2b1.s, src/kernels/conv5x10u2v2f1.s, src/kernels/conv7x7c3h224w224k64u2v2p3q3f1.s
Fixes value of `.max_flat_workgroup_size` in the metadata of three assembly kernels (`miopenConv5x10u2v2b1`, `miopenConv5x10u2v2f1`, `miopenGcnAsmConv7x7c3h224w224k64u2v2p3q3f1`). Resolves the following issues:
- https://ontrack-internal.amd.com/browse/SWDEV-277901
- https://ontrack-internal.amd.com/browse/SWDEV-286069
=> Fix .max_flat_workgroup_size (SWDEV-277901, SWDEV-286069)

Dockerfile, src/include/miopen/mlir_build.hpp, src/mlir_build.cpp, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_wrw.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp
This PR does the following:
- Refactored all non-xdlops solvers to take advantage the `MiirIsConfigApplicable()` check to make sure no false positive exist
- Bumped the MLIR commit
- Introduced the MiirGetKernelCount() API to pave road for multi-kernel compilation
---
Previous PRs in the series:
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/841
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/889
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/892
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/902
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/912
=> [MLIR] Binary backend - step 6 - Introduce GetKernelCount API

src/conv/invokers/mlir_impl_gemm.cpp, src/include/miopen/solver/mlir_common.hpp, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_bwd_xdlops.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp, src/solver/conv_mlir_igemm_wrw.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp, src/solver/mlir_common.cpp
*Please note: this PR can not and should not be tested because MLIR support for it is not there yet. Since both bwd and bwd_xdlops solvers are also disabled, running CI through does not exercise those two solvers. I am pushing those changes hoping that this will simplify the final bring up process.*
- *If things are working as expected when MLIR add support for both solvers, the only thing needs to be done in MIOpen side is to bump the MLIR commit id/ add bwd unit tests.*
- *If anything else needs to be adjusted, further PR will be filed to update the MIOpen side of the implementation.*
----
This PR does the following:
- Used the MiirGetKernelCount() API for kernel count in bwd solvers
- Implement v4r1 bwd multi-kernel compilation in bwd solvers
- This replaced the original v1r1 …
=> [MLIR] Binary backend - step 7 - Implement v4r1 algorithm for bwd solvers

src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp, test/CMakeLists.txt
To fix issue: #917 
test by :
```
MIOPEN_FIND_MODE=normal MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvHipImplicitGemmBwdDataV4R1Xdlops MIOPEN_LOG_LEVEL=5 ./bin/test_conv2d --half --input 8 16 14 14 --weights 32 16 1 1 -v --disable-backward-weights --disable-forward --pads_strides_dilations 1 1 1 1 1 1
```
and get output:
```
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --disable-forward --disable-backward-weights --input 8, 16, 14, 14 --weights 32, 16, 1, 1 --pads_strides_dilations 1 1 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
error: 0
Max diff: 0
Backward convolution: ConvHipImplicitGemmBwdDataV4R1Xdlops
Input tensor: 8, 16, 14, 14
Weights tensor: 32, 16, 1, 1
Output tensor: 8, 32, 16, 16
```
=> Fix restrictions for vecload condition (iGemm v4r1 Bwd, 1x1)

CONTRIBUTING.md
Add a contributing guide to the MIOpen repository. Please review the document and provide comments and suggestions below.
=> Adding MIOpen Contributing Guide

src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_reduction.hpp, src/kernels/composable_kernel/include/kernel_algorithm/reduction_kernel_simple_configurator.hpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction.cpp, src/reducetensor.cpp, test/reduce_test.cpp
This is pushed in order to solve the issue raised by [SWDEV-284291](https://ontrack-internal.amd.com/browse/SWDEV-284291)
Regular testing has passed on (rocm-3.10,rocm-3.7,rocm-4.2)/MI00,  rocm-4.2/MI25, rocm-4.2/Navi21, rocm-3.10/MI60 
Method for regular testing
`#>bin/test_reduce_test --all`
`#>bin/test_reduce_test --half --all`
=> Fix missing padding of the transformed 2d-src and 1d-dst tensors in Generic-Tensor Reduction (SWDEV-284291)

src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp, test/CMakeLists.txt
Resolves #948. K need be multiple of gemm_k_per_block when thread_length have value not equal to 1.
test passed according to config from https://github.com/ROCmSoftwarePlatform/MIOpen/pull/945#issuecomment-846305287
```
MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvAsmImplicitGemmGTCDynamicBwdXdlops  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt//conda/lib/ MIOPEN_LOG_LEVEL=5 MIOPEN_FIND_MODE=1 ./bin/MIOpenDriver convfp16 -n 8 -c 16 -H 5 -W 5 -k 8 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 -V 1 2>&1 | tee log.txt
MIOpenDriver convfp16 -n 8 -c 16 -H 5 -W 5 -k 8 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 -V 1
MIOpen(HIP): Info [get_device_name] Raw device name: gfx908:sramecc+:xnack-
MIOpen(HIP): Info [Handle] stream: 0x1ae3c30, device_id: 0
MIOpen(HIP): Info …
```
=> Fix NCHW bwd asm igemm solver. Remove WORKAROUND_SWDEV_286774.

driver/driver.hpp, driver/main.cpp, driver/miopen_Reduction.hpp, driver/reduce_driver.hpp, include/miopen/miopen.h, src/gemm_v2.cpp, src/include/miopen/conv/problem_description.hpp, src/include/miopen/datatype.hpp, src/include/miopen/tensor.hpp, src/include/miopen/visit_float.hpp, src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp, src/ocl/tensorocl.cpp, src/reducetensor.cpp, src/solver/conv_asm_1x1u.cpp, src/tensor.cpp, test/CMakeLists.txt, test/driver.hpp, test/reduce_test.cpp, test/tensor_holder.hpp, test/tensor_vec.cpp
Adds `miopenDouble` to the public API.
Adds support for miopenReduceTensor() to be used on Tensors of double type data. All the 8 Reduction Operations which are supported with fp32/fp16 Tensors can be used with double Tensors. The alpha/beta scaling factors follow the same specification as what is used by cuddnReduceTensor(),  that is,  for fp32/fp16, alpha/beta should be float type passed by the application; for double, alpha/beta should be double type passed by the application.
This is expected to resolve https://ontrack-internal.amd.com/browse/SWDEV-284915.
<details><summary><b><i>The commits have gone through the following tests:</i></b></summary>
Regular MIOpen tests:
```bash
$ ./bin/test_reduce_test --double --all
$ ./bin/test_reduce_test --all
$ ./bin/test_reduce_test --half --all …
```
=> Generic Tensor Reduction for Double (SWDEV-284915)

CMakeLists.txt
Header filter works wrong if path contains 'hpp' substring.
1 jenkins run shows this error.
=> Fix for tidy failures when branch name contains 'hpp'

src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp
This resolve [SWDEV-291574](https://ontrack-internal.amd.com/browse/SWDEV-291574) issue by removing the duplicated `group` divide while calculating k_per_block, since `k` already divided by `group` in above [L796](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp#L796).
After this fix, the original problematic config `./bin/MIOpenDriver convfp16 -n 64 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 2 -t 1` should not be valid for this asm solver, since `c_per_bloc = 256/32 = 8`, `k_per_bloc = 256/32 = 8`, this is too small for NCHW asm igemm to support (NCHW fp16 does not support pack c or k)
Beside, if reduce group size to like 2, 4, 8, 16, the solver can successfully calculate the result. …
=> [HOTFIX] Remove duplicated group divide when calculation k per group (SWDEV-291574)

Dockerfile, src/conv/invokers/mlir_impl_gemm.cpp, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_bwd_xdlops.cpp, test/CMakeLists.txt
This PR does the following:
- Enabled ConvMlirIgemmBwd and ConvMlirIgemmBwdXdlops solvers
- Forwarded the MLIR commit to the latest
- Bumped cmake version to 3.15.1
- Note: next step we will build artifact and thus not dependent on MIOpen docker builds
- Brought in the updated MLIR library installation commands
- Fixed a number of problems exposed from the bwd solver bring up process
- Inversion of input/output tensor in the invoker
- Permutation of strides/dims happen before insertion of virtual G dimension
- Initialization of StridedMemRef5D
- Added unit test that test the bwd solvers in following conditions
- fp32/fp16
- NCHW/NHWC
- group
----
This PR is the last MLIR binary backend PR. Previous PRs in the series:
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/841 …
=> [MLIR] Binary backend - step 8/of 8 - Bring up and enable bwd solvers

test/CMakeLists.txt
https://ontrack-internal.amd.com/browse/SWDEV-291479:
> **_It is urgent to resolve this error in Staging in order to continue the normal MIOpen promotion process._** Until the bug in the compiler (SWDEV-274384) is fixed, the only way to do it that I can see right now is to disable test_reduce_double.
=> [HOTFIX][WORKAROUND] Disable test_reduce_double (SWDEV-291479)

Jenkinsfile, test/CMakeLists.txt
- Added: Workarounds for #995 and #996
- Fixes the following issues in tests (see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/990#issuecomment-864467122 for details):
- Issue: `test_conv_igemm_dynamic_xdlops_bwd` does not test the HALF type.
- Issue: `test_conv_igemm_dynamic_xdlops_fwd` does not test the HALF type.
- Issue: `test_conv_igemm_dynamic_xdlops_wrw` does not test the HALF type.
- Issue: `test_regression_half_vega` does nothing.
- [Jenkinsfile] Added dedicated build param for FP16/BF16/INT8 Smoke tests
- [NFC] Removed some useless if's.
:warning: To reviewers: First of all, I ask you to understand what was wrong before.
=> [TESTS][FP16][WORKAROUND] Fix test_conv_igemm_dynamic_xdlops* and test_regression_half_vega. W/A for #995 and #996

src/binary_cache.cpp, src/expanduser.cpp, src/hip/handlehip.cpp, src/hipoc/hipoc_program.cpp, src/include/miopen/expanduser.hpp, src/include/miopen/stringutils.hpp
This is expected to resolve issue #962 by removing W/A for https://ontrack-internal.amd.com/browse/SWDEV-225285. That SWDEV is fixed in ROCm 3.4 which we do not support anymore. Some stale review comments from #307 resolved as well.
- [NFC] Allowed `ReplaceString()` to accept const reference on input.
- [NFC] Resolved https://github.com/ROCmSoftwarePlatform/MIOpen/pull/307#discussion_r513634922
- [NFC] Resolved https://github.com/ROCmSoftwarePlatform/MIOpen/pull/307#discussion_r513635358
- [NFC] Partially resolved https://github.com/ROCmSoftwarePlatform/MIOpen/pull/307#discussion_r513645212
- [NFC] Resolved https://github.com/ROCmSoftwarePlatform/MIOpen/pull/307#discussion_r513662388
- Removed `MIOPEN_WORKAROUND_SWDEV_225285`
/cc @zpwenjh
=> Remove W/A for SWDEV-225285

src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp, src/kernels/composable_kernel/include/utility/reduction_common.hpp, src/kernels/composable_kernel/include/utility/reduction_operator.hpp, src/reducetensor.cpp, test/CMakeLists.txt, test/reduce_test.cpp
1)  The first commit is supposed to prevent the failure of lost index updates reported in [SWDEV-291479](https://ontrack-internal.amd.com/browse/SWDEV-291479) and [SWDEV-274384](https://ontrack-internal.amd.com/browse/SWDEV-274384)
2) The second commit is supposed to prevent the  failure of all-zero accumulated output (both cpu and gpu) for some reduce_test cases
3) The third commit is for fixing one potential issue. 
- The P.R has passed the following test 
```bash
bin/test_reduce_test --all  --double
bin/test_reduce_test --all
bin/test_reduce_test --all --half
```
- About the Performance 
No performance loss was seen when running `bin/test_reduce_test --all`  on cached binary kernels produced with or without this P.R
=> [WORKAROUND] Generic-Reduction: Partially resolve SWDEV-291479. W/A for SWDEV-274384.

src/include/miopen/conv/invokers/impl_gemm_dynamic.hpp, src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
This fix https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1005. Indeed only two solver affected:
`ConvAsmImplicitGemmGTCDynamicFwdXdlops`
`ConvAsmImplicitGemmGTCDynamicWrwXdlops`
Other solver do not have this problem
=> [ASM IGEMM][MI100] refactor solver, remove duplicated copy of pointers

src/kernels/composable_kernel/include/utility/synchronization.hpp
remove __llvm_amdgcn_s_barrier(), which is not used but trigger compilation error because of function naming
https://ontrack-internal.amd.com/browse/SWDEV-274384
=> [Navi21] Fix generic reduction kernels by removing __llvm_amdgcn_s_barrier (SWDEV-274384)

src/include/miopen/solver_id.hpp, src/ocl/convolutionocl.cpp, src/solver.cpp
This allows one to fetch the primitive of a solver id or a vector of solver ids for the specified primitive.
=> [Tuna] Updated solver id to include primitive.

src/md_graph.cpp, test/mdgraph.cpp
This PR fixes missing fused asm1x1 _**supported arch**_ restrictions (see #706).
This bug could lead to failure while creating _Convolution+Bias+Activation_ Fusion Plan with unsupported arch:
```
MIOpen(HIP): Info2 [AmdgcnAssemble] ' -x assembler -target amdgcn--amdhsa  -Wa,-defsym,stride_h=1 -Wa,-defsym,stride_w=1 -Wa,-defsym,img_h=56 -Wa,-defsym,img_w=56 -Wa,-defsym,batch_size=1 -Wa,-defsym,input_channels=64 -Wa,-defsym,output_channels=64 -Wa,-defsym,wei_h=1 -Wa,-defsym,wei_w=1 -Wa,-defsym,pad_h=0 -Wa,-defsym,pad_w=0 -Wa,-defsym,weights_layout=0 -Wa,-defsym,vec_c_in=1 -Wa,-defsym,vec_k_out=1 -Wa,-defsym,vec_c_filter=1 -Wa,-defsym,acc_type=1 -Wa,-defsym,buf_type=1 -Wa,-defsym,input_n_stride=802816 -Wa,-defsym,input_c_stride=12544 -Wa,-defsym,input_h_stride=224 …
```
=> Fix fusions asm1x1 supported arch

CMakeLists.txt, Dockerfile, Jenkinsfile, test/CMakeLists.txt
Implements #985 
* [TESTS] Added detection of GPU type for testing.
* Explicit setting of `MIOPEN_TEST_GFX*` overrides it (for backward compatibility).
* [Jenkinsfile] Removed explicit setting of the MIOPEN_TEST_GFX908 flag because it is not required anymore.
* [Dockerfile] Installed `kmod` as it is required by `rocminfo` to work.
- The default GPU for testing was gfx900/906 (Vega) before this PR. Now the default GPU for testing is identified by grepping the output of `rocminfo`.
- If `rocminfo` is not available or fails, then `make check` fails immediately. In this case the user need to explicitly specify `MIOPEN_TEST_GFX908=On` or `MIOPEN_TEST_VEGA=On` etc. _Before this PR_, Vega testing was enabled by default in this case.
- Ditto if detected GPU is not known to the …
=> [TESTS] Detection of GPU type (SWDEV-290980)

Dockerfile, src/include/miopen/solver/implicitgemm_util.hpp, src/mlir_build.cpp, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_bwd_xdlops.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp, src/solver/conv_mlir_igemm_wrw.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp, src/solver/mlir_common.cpp
Some of the checks that the MLIR solvers perform can be moved into
MLIR, allowing MLIR to enable support for more types of convolution
without needing to coordinate as many changes with MIOpen. This also
reduces redundancy in the solver applicability checks.
=> [MLIR] Remove validations that have been moved into MLIR.

src/md_graph.cpp
This PR resolves #1028 ([details here](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1028#issuecomment-877467684))
The ConvOclDirectFwdFused solver does not support 1x1 convolutions whereas the metadata graph encodes it as applicable which causes issues.
=> Fix: Remove 1x1 applicable from OclDirectFused

src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp
Reverts #982. Partial W/A for FP32 SSD issue (memory access fault in https://ontrack-internal.amd.com/browse/SWDEV-295434).
:warning: Merging this will cause #980 to appear again!
=> [HOTFIX][WORKAROUND] Revert #982 -- partial W/A for FP16 SSD issue (memory access fault in SWDEV-295434)

Jenkinsfile, test/CMakeLists.txt
Partially (FP32 for OCL backend) implements issue #1022.
- Added Smoke and Full FP32 testing stages for Navi21 with **_OpenCL_** backend.
- Why not HIP backend: HIP compiler as of 4.2 does not support gfx1030 by default, as well as rocBLAS etc. Therefore we need to wait for 4.3 release before enabling gfx1030 testing with HIP backend. Symptom: `"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"` More info about this problem is available [at this private link](http://gerrit-git.amd.com/c/compute/ec/hip/+/519434/5/docs/markdown/hip_faq.md). However, the most of the Navi21 functionality can be tested with OpenCL from 4.2.
- Added W/A for issue #1053.
=> [CI][TESTS][Navi21] Basic support for Navi21

src/kernels/batchnorm_functions.h, src/kernels/reduction_functions.h
Also fixes potential bug because `MIOPEN_USE_AMDGCN` should not be defined for gfx1030.
=> [Navi21][HOTFIX] Fix kernel build issues introduced in PR #1037

CMakeLists.txt
Bump up the MIOpen version to 2.14 (after cutting the rocm-rel-4.4 branch)
=> Bump up the MIOpen version to 2.14 (after cutting the rocm-rel-4.4 branch)

test/CMakeLists.txt
After enablement of #1024 MIOpen cannot build successfully on GPU-less platforms, such as WSL environment
This PR fixes #1080
=> [NOGPU] Fix #1080 enable MIOpen builds on GPU-less

src/reducetensor.cpp
This PR is necessary to get the correct kernel profiling for reduction operation when tested using  `MIOpenDriver reduce xxx -t 1`.  The `MultiBlock` method of implementing reduction operation uses hierarchical kernel calls,  and in that case,  without the fix by this P.R, the kernel execution time returned by `MIOpenDriver reduce xxx -t 1`  only counts for the execution time of the second kernel call.
=> Fix the timing for reduction kernels

src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_blockwise.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_threadwise.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_direct_warpwise.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_2d_reduction_multiblock.hpp, src/kernels/composable_kernel/include/kernel_algorithm/gridwise_generic_reduction.hpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_first_call.cpp, src/kernels/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_second_call.cpp, src/reducetensor.cpp
This P.R improve the compiling time of the reduction kernels by:
1.  Split the two kernels into two .cpp files so that the other kernel is not compiled while compiling this kernel
2.  Replace the Run() and Run_2() interfaces of gridwise_generic_reduction by one templated Run() interface so that one interface is compiled for one kernel call
3.  Replace the using of static_if<> inside Run() of gridwise_generic_reduction by templated Run() since static_if<> seems could not avoid compiling of the false branch
4.  Replace the RunImpl1/RunImpl2/RunImpl2 interfaces in specific ThreadWise/WarpWise/BlockWise/MultiBlock kernels  by template Run()
This P.R also avoid possible compile-time failures due to evaluating the constexpr values from the codes that should not be compiled.
=> Improve the compiling of reduction kernels

src/ocl/convolutionocl.cpp, src/reducetensor.cpp, src/solver/activ/bwd_0.cpp, src/solver/conv_ocl_dir2D_bwdWrW_2.cpp, test/conv_common.hpp, test/tensor_transform.cpp
This fixes some issues found with a newer version of cppcheck, but not all(as such the cppcheck version is not updated in this PR). This does find some serious bugs, like using the x desc instead of y desc and incorrect check for `NCDHW` layout, so we should probably merge these fixes in. 
----
@atamazov 
- :red_circle: Fixes a bug in activation
- :yellow_circle: Fixes a bug in _convolution_ ___tests___
=> Some cppcheck fixes

src/include/miopen/solver.hpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp
* Implemented the `PerformanceConvMlirIgemmXdlops` that will be shared across fwd/bwd, and wrw solvers
* The library side behaves like below:
* If no perfConfig is passed in, do heuristic intialization
* If a perfConfig is passed in, use and only use this perfConfig (for non-padding kernel)
------
Test performed:
> MIOPEN_FIND_ENFORCE=4 MIOPEN_LOG_LEVEL=6 MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmFwdXdlops ./bin/MIOpenDriver conv -F 1 -n 256 -c 1024 -H 14 -W 14 -k 2048 -y 1 -x 1 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -t 1 -V 0
Test log:
> MIOpen(HIP): Warning [GenericSearch] Done: 404/0/404, best # 90 2.13993 256,128,8,128,64,1,1,1
Time spent in tune one config: 63.64 seconds
---
Previous PR this series: 
- #1075
=> [MLIR] Implement tuning - step 2: fwd, xdlops

Jenkinsfile
[Purpose]
Move Navi21 tests to optional stages and run nightly only **temporarily**
[Trigger Condition to *Ready for Review*]
- [Completed] CI has passed
- [AND] [Still observed] gfx1030 still not stable for develop branch for at least 2 consecutive days
- [OR] [not a blocking issue] gfx1030 CI resource availability fall short
[Actions when the above triggers condition is met]
- [[comment]](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1135#issuecomment-916461804) The unit test failures should be documented clearly
- [Open for review] Merge this PR (convert to ready for review first)
- [TBD] Set up nightly gfx1030 check separately
=> [TESTS][Navi21][WORKAROUND] Move Navi21 tests for release schedule

src/ocl/batchnormocl.cpp, src/solver/conv_MP_bidirectional_winograd.cpp, src/solver/conv_asm_1x1u.cpp, src/solver/conv_asm_1x1u_stride2.cpp, src/solver/conv_asm_3x3u.cpp, src/solver/conv_asm_5x10u2v2b1.cpp, src/solver/conv_asm_5x10u2v2f1.cpp, src/solver/conv_asm_7x7c3h224w224k64u2v2p3q3f1.cpp, src/solver/conv_asm_dir_BwdWrW1x1.cpp, src/solver/conv_asm_dir_BwdWrW3x3.cpp, src/solver/conv_asm_implicit_gemm_bwd_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp, src/solver/conv_asm_implicit_gemm_v4r1_dynamic.cpp, src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp, src/solver/conv_asm_implicit_gemm_wrw_v4r1_dynamic.cpp, src/solver/conv_bin_wino3x3U.cpp, src/solver/conv_bin_winoRxS.cpp, src/solver/conv_multipass_wino3x3WrW.cpp, src/solver/conv_winoRxS_f2x3.cpp, src/solver/conv_winoRxS_f3x2.cpp, test/CMakeLists.txt
By @atamazov: From now on we need to officially support XNACK enabled GPUs. This PR adds very simple support in Solvers that use ASM kernels: so far, none ASM kernels were are ready for XNACK enabled GPUs, so we need to disable them.
Also reverts some incorrect fixes introduced in #809 and #1110 (details [here](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1142#issuecomment-914681719))
<details><summary><b><i>Previous version of description</i></b></summary><hr>
As I [mentioned](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1093#issuecomment-914586825) in the #1093, some asm kernels may not support **xnack**, but this is not checked anywhere.
This pull request temporarily disables all asm solvers if **xnack** is enabled.
Next, asm kernels must be checked for support …
=> Explicitly disable asm solvers if XNACK is enabled

src/ocl/batchnormocl.cpp
`checkNumericsOutput` calls have been skipped on the second and later invocations of the bnorm forward function.
=> Fixed missing checkNumericsOutput in bnorm forward

cmake/DoxygenDoc.cmake, cmake/MainDoc.cmake, cmake/SphinxDoc.cmake, doc/CMakeLists.txt
As mentioned in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1074, proper documentation is generated only after second "make doc". This PR fixes it. Also "make clean" does not remove all generated files in doc/src (see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1073). This is also fixed.
Fixes https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1073
Fixes https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1074
=> [Doc] Proper documentation generating and cleaning

src/include/miopen/solver.hpp, src/include/miopen/solver/mlir_common.hpp, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_bwd_xdlops.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp, src/solver/conv_mlir_igemm_wrw.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp, src/solver/mlir_common.cpp
- Enabled tuning for bwd, and bwd xdlops solver
- Reused the previously available `PerformanceConvMlirIgemm` for bwd solver
- Reused the previously available `PerformanceConvMlirIgemmXdlops` for bwd xdlops solver
- Refactored the solver infrastructures in `mlir_common.cpp`
- Moved the `GetKernelName()` and `GetOperation()` into it to make it solver independent
- Removed those two functions from all solvers
- [TODO] Will consider about making it into a class in the future.
Command:
>  MIOPEN_FIND_ENFORCE=4 MIOPEN_DRIVER_USE_GPU_REFERENCE=1 MIOPEN_LOG_LEVEL=6 MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmBwd ./bin/MIOpenDriver conv -F 2 -n 256 -c 64 -H 56 -W 56 -k 64 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1 -V 1
Log:
> MIOpen(HIP): Warning [GenericSearch] …
=> [MLIR] Implement tuning - step 3: bwd, nonxdlops + xdlops

test/CMakeLists.txt
**Updated description:**
After merging #1129, issues #1064 and #1095 are no longer observed, so no workaround is needed for them.
Fix #1064 #1095 remove work arounds for test_dropout
test_dropout only runs one iterations now and should not be very long
will monitor CI for progress
=> [Test][CI] Fix #1064 #1095 remove work arounds for test_dropout

Jenkinsfile
- New feature: Now you can select subset of GPU types for testing.
- How: https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-manually-run-CI-job-with-parameters.
By-products:
- Re-implements #1135
- :warning: ___Quiet change: The [`MIOPENNAVI21`](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1148#issuecomment-916656557) parameter renamed to___ `FULL_TESTS_NAVI21_OPTIONAL`.
- Testing quality: Removed `WORKAROUND_iGemm_936` from FP32. This should resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/147/files#r706276953
- Refactorings:
- Removed redundant DISABLE_ALL_STAGES parameter
- Refactored SMOKE_MIOPENTENSILE_LATEST
- Removed unused BUILD_PACKAGES
- Formatting fixes
=> [CI] Add capability to select GPU type for testing.

src/CMakeLists.txt, src/kernels/Conv_Winograd_v21_1_2_f3x2_fp32_stride1_group.s, src/kernels/Conv_Winograd_v21_1_2_gfx90a_f3x2_fp32_stride1_group.inc, src/solver/conv_winoRxS_f3x2.cpp
This PR adds Winograd f3x2 fp32 support for gfx90a. Partially resolves issue https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/2.
- gfx90a, rocm 4.3.1
<details><summary>Test cases</summary>
-W | -H | -c | -n | -k | -x | -y | -q | -p | -u | -v | dir
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
17 | 17 | 128 | 32 | 128 | 7 | 1 | 3 | 0 | 1 | 1 | fwd/bwd/wrw
17 | 17 | 128 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | fwd/bwd/wrw
17 | 17 | 160 | 32 | 160 | 7 | 1 | 3 | 0 | 1 | 1 | fwd/bwd/wrw
17 | 17 | 160 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | fwd/bwd/wrw
17 | 17 | 192 | 32 | 192 | 7 | 1 | 3 | 0 | 1 | 1 | fwd/bwd/wrw
17 | 17 | 192 | 32 | 224 | 7 | 1 | 3 | 0 | 1 | 1 | fwd/bwd/wrw
17 | 17 | 224 | 32 | 224 | 7 | 1 | 3 | 0 | 1 | 1 | fwd/bwd/wrw
17 | 17 | 256 | 32 | 256 | 7 | 1 | 3 | …
=> [gfx90a] Winograd f3x2 fp32 support

src/batchnorm/problem_description.cpp, src/include/miopen/batchnorm/invoke_params.hpp, src/include/miopen/batchnorm/problem_description.hpp, src/ocl/batchnormocl.cpp
This PR updates `batchnorm::ProblemDescription`, implements `batchnorm::BwdInvokeParams`, and updates `BatchNormBackward`.
Splitting it to a separate branch allows for making backward solver PRs in parallel rather than sequentially and eases the review by splitting the source.
=> [NFC] Batchnorm backward solvers core

src/kernels/conv3x3wrw.s, src/solver/conv_asm_dir_BwdWrW3x3.cpp
This PR adds Direct conv3x3wrw support for gfx90a. Partially resolves issue ROCmSoftwarePlatform/MIOpen-internal#2.
- gfx90a, rocm 4.3.1
<details><summary>Test cases</summary>
type | -W | -H | -c | -n | -k | -x | -y | -p | -q | -u | -v | -F | -g
--   | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
fp16/fp32 | 7 | 7 | 160 | 32 | 224 | 3 | 3 | 1 | 1 | 1 | 1 | wrw | 1
fp16/fp32 | 7 | 7 | 160 | 32 | 224 | 3 | 3 | 1 | 1 | 1 | 1 | wrw | 4
fp16/fp32 | 7 | 7 | 160 | 32 | 320 | 3 | 3 | 1 | 1 | 1 | 1 | wrw | 1
fp16/fp32 | 7 | 7 | 160 | 32 | 320 | 3 | 3 | 1 | 1 | 1 | 1 | wrw | 4
fp16/fp32 | 7 | 7 | 160 | 128 | 320 | 3 | 3 | 1 | 1 | 1 | 1 | wrw | 1
fp16/fp32 | 7 | 7 | 160 | 128 | 320 | 3 | 3 | 1 | 1 | 1 | 1 | wrw | 4
fp16/fp32 | 7 | 7 | 192 | 32 | 224 | 3 | 3 | 1 | 1 | 1 | 1 | wrw | …
=> [gfx90a] Direct conv3x3 wrw support

Dockerfile, src/include/miopen/solver.hpp, src/include/miopen/solver/mlir_common.hpp, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_bwd_xdlops.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp, src/solver/mlir_common.cpp
This address #1154 
Quote from @atamazov's proposal below:
- Modify GetPerformanceConfig() to return a special value (all -2) to ask MLIR to perform heuristic init
- PerformanceConvMlirIgemm::IsValid(HeuristicInitRequest) return true
- PerformanceConvMlirIgemm::SetNextValue(HeuristicInitRequest) return false
- Modify mlir::ConstructBuildOptions() treate HeuristicInitRequest as a special value.
Note: 
- commit 055906b only address one solver
- If you agree with my existing approach, I will apply the same fix to rest of xdlops/nonxdlops, fwd/bwd solvers in next commit
-----
Previous PR this series: 
- #1075
- #1139
- #1152
=> [MLIR] Implement tuning - step 4: Use special value to represent default perf_config

Dockerfile, Jenkinsfile
- [CI] HOTFIX: Create `render` group in the docker image. Add jenkins user to `render` group for Ubuntu 20.04. 
- [CI] Fix: evaluate TARGET param in 'when' before entering agent.
- [CI] Fix strange syntax errors
Resolves the following issues:
- :red_circle: CI fails on nodes with Ubuntu 20.04 (I see this on gfx90a nodes at least)
- :yellow_circle: CI tests takes too long time if subset of TARGETS is selected
See https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#setting-permissions-for-groups.
> @junliume ...observed here: jenkins / MLLibs/MIOpen / wip-rocmtest-trial-vega10 / #50 (amd.com).  It seem that several parallel stages are queued where they should not...
>
> Run `#50` timed out after 5 hours. Yes, the three “green” ones are needed and correct behavior. …
=> [CI] HOTFIX: Support Ubuntu 20.04. Fix: evaluate TARGET param in 'when' before entering agent. Syntax fixes/workarounds.

src/include/miopen/solver.hpp, src/solver/conv_mlir_igemm_wrw.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp
- Enabled tuning for wrw, and wrw xdlops solver
- Reused the previously available `PerformanceConvMlirIgemm` for wrw solver
- Reused the previously available `PerformanceConvMlirIgemmXdlops` for wrw xdlops solver
```bash
MIOPEN_FIND_ENFORCE=4 MIOPEN_DRIVER_USE_GPU_REFERENCE=1 MIOPEN_LOG_LEVEL=6 MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmWrW ./bin/MIOpenDriver conv -F 4 -n 256 -c 64 -H 56 -W 56 -k 64 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1 -V 1
```
> MIOpen(HIP): Warning [GenericSearch] Done: 21/0/21, best # 7 235.356 128,64,32,16,2,2
```bash
MIOPEN_FIND_ENFORCE=4 MIOPEN_DRIVER_USE_GPU_REFERENCE=1 MIOPEN_LOG_LEVEL=6 MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmWrWXdlops ./bin/MIOpenDriver conv -F 4 -n 256 -c 64 -H 56 -W 56 -k 64 -y 1 -x …
```
=> [MLIR] Implement tuning - step 5 of 5: wrw, nonxdlops + xdlops

Dockerfile, mlir-requirements.txt
I did some additional cmake tweaks in MLIR end and tested to make sure things are compatible with cget now.
@JehandadKhan After this is merged, you should be able to take advantage if the `mlir-requirements.txt` to parse the newest available mlir commit.
=> [MLIR] Switch to cget installation

Dockerfile
I get reminded by @JehandadKhan that MLIR used a different ROCm version then rest of stages. Bumping them to parallel version now.
=> [MLIR] Bump ROCm version to 4.3.1

src/convolution.cpp, src/find_controls.cpp, src/include/miopen/find_controls.hpp, src/include/miopen/find_solution.hpp, src/include/miopen/stringutils.hpp
This PR allows MIOPEN_DEBUG_FIND_ONLY_SOLVER to comprise of multiple solvers separated by semicolon. For example, when debugging issues in frameworks, one needs multiple solvers (different directions). This PR enables such a functionality.
=> accept list of solvers in MIOPEN_DEBUG_FIND_ONLY_SOLVER

src/solver/conv_bin_wino3x3U.cpp
This PR removes winograd-3x3u workaround for gfx90a. Details [here](https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/2#issuecomment-928098626).
=> [gfx90a] Finally disable ConvBinWinograd3x3U

src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
This is W/A for #1206: #1207 ported for develop to unblock MIOpen promotion pipeline.
=> [HOTFIX][WORKAROUND] #1207 ported to develop: W/A for issue 1206. Disable ConvHipImplicitGemmBwdDataV4R1Xdlops by default

src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
Removes FP32 ConvHipImplicitGemmBwdDataV4R1Xdlops from find_db replacing with second best Backward Data Implicit GEMM solver.
=> [Tuning] Remove Solver ConvHipImplicitGemmBwdDataV4R1Xdlops FP32

Jenkinsfile, test/CMakeLists.txt
This PR should address https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1069. Although I'd appreciate the reviewer to give me early feedback on whether this is done in the right way (So that I don't have to try random things and keep MIOpen CI spinning).
This PR does the following (Trying to follow what has been done to `test_conv_igemm_dynamic` test):
- Cherry picked configs into `test_conv_igemm_mlir_*_small` stages and make them guarded by `CODECOV_TEST`
- Added `Smoke_targets` in jenkinsfile
After this PR, MIOpen will test mlir configs in smoke targets only, and lose the full test coverage. However, those full test coverage will be regained in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1228 (Once MLIR become a default dependency). Since both PRs are targeted to merge by …
=> [MLIR] Separate small MLIR tests to smoke stages

Dockerfile, README.md, dev-requirements.txt, install_deps.cmake, min-requirements.txt, mlir-requirements.txt, rbuild.ini, requirements.txt
This removes the old hcc dependencies in our requirements.txt files. Now min-requirements.txt and requirements.txt are the same(we could hopefully remove this file in the future).
I also moved the cmake installation to mlir-requirements.txt, since its purpose is for mlir. I am not sure why it installs to /opt/rocm instead of `$PREFIX` but I didnt change this just in case mlir has a broken cmake installation(we should be able to install mlir to any `$PREFIX` using cget and it should work without needing private env variables(ie ROCM_PATH, HIP_PATH, etc) but I havent tested this).
This also adds an rbuild.ini file which has different sessions to build dependencies and settings. It will set the clang compiler by default(for rocm releases), so users can build by just doing `rbuild build -d …
=> [Enhancement] Simplify dependencies to build

src/include/miopen/conv/problem_description.hpp, src/solver/conv_asm_1x1u.cpp, src/solver/conv_asm_1x1u_stride2.cpp, src/solver/conv_asm_dir_BwdWrW1x1.cpp, src/solver/conv_asm_dir_BwdWrW3x3.cpp, src/solver/conv_bin_winoRxS.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_winoRxS_f2x3.cpp, src/solver/conv_winoRxS_f3x2.cpp
- Simplify access to ALT attribute from ProblemDescription
- ConvBinWinogradRxSf2x3, ConvBinWinogradRxSf2x3g1
- ConvBinWinogradRxSf3x2
- ConvAsm1x1U, ConvAsm1x1UV2
- ConvAsmBwdWrW1x1, ConvAsmBwdWrW3x3
- ConvHipImplicitGemmBwdDataV1R1, ConvHipImplicitGemmBwdDataV1R1Xdlops
- ConvHipImplicitGemmBwdDataV4R1Xdlops
- ConvHipImplicitGemmForwardV4R4Xdlops, ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm
- ConvHipImplicitGemmForwardV4R5Xdlops
- ConvHipImplicitGemmV4R1Fwd, ConvHipImplicitGemmV4R1WrW
- ConvHipImplicitGemmWrwV4R4Xdlops, ConvHipImplicitGemmWrwV4R4Xdlops_Padded_Gemm
- Not necessary for:
- ConvBinWinogradRxS due to [this reasoning](https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/2#issuecomment-919021192).
- ConvHipImplicitGemmBwdDataV4R1, ConvHipImplicitGemmV4R4Fwd, …
=> [gfx90a][FP16] Disable Solvers that unable to comply the "ALT FP16" attribute

driver/CBAInferFusion_driver.hpp, driver/conv_driver.hpp, driver/driver.hpp, driver/miopen_ConvBatchNormActivHost.hpp
This PR fixes _CBAInfer_ driver bug.
`miopenInferVerify` always returns `1`. Due to this, the _CBAInfer_ verification was successful even if it was not.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f02d9598fc02ad4fbf67d4f1cd88ed4e296f0961/driver/CBAInferFusion_driver.hpp#L1185-L1190
=> [BugFix] CBAInfer verification

src/comgr.cpp, src/hip/hip_build_utils.cpp, src/kernels/static_composable_kernel/include/utility/static_kernel_amd_buffer_addressing.hpp
This is urgent PR that is expected to unblock hip promotion (https://ontrack-internal.amd.com/browse/SWDEV-310166).
- [HIP offline build] Remove x86 builtin lib from linking.
- [COMGR] Remove x86 builtin lib from linking more reliably.
- By-products
- [Future ROCm] Disable `-Wreserved-identifier` for declarations of llvm intrinsics in HIP kernels. Otherwise DEV builds fail at runtime, during HIP compilation (due to -Werror).
=> Fix HIP builds for the upcoming HIP compiler (SWDEV-310166)

CMakeLists.txt, Jenkinsfile, src/comgr.cpp, test/CMakeLists.txt
Resolves (hides symptoms of) https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/4 and https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1257.
- Reverted #1253 
- Kept some useful stuff for CMake + tidy fixes for 4.5
- Added regression test for https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/4
[Informative] Actual problem is that kernels built via COMGR may have correctness problems (we know some cases for gfx90a).
=> [HIP][COMGR] Abstain from COMGR by default for HIP backend (revert #1253). Add regression test for issue-internal #4

src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
fix a bug in when heuristic init asm igemm fwd/bwd/wrw. Previously config like:
`./bin/test_conv2d --half --verbose --input 120 512 19 19 --weights 510 512 3 3  --pads_strides_dilations 1 1 1 1 1 1 --disable-backward-data --disable-backward-weights  --in_layout NHWC --fil_layout NHWC --out_layout NHWC `
will fail. This is due to a bug in heuristic init. If we run with `FIND_ENFORCE=4`, or tune the db, then everything is OK.
[informative] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1267/commits/27c8024374393e40d8ce9f904925406b00bf9bea message is not correct, actually wrw also have bug when heuristic init. bug is fixed and double checked SSD can converge
=> [BugFix] asm igemm heuristic init, for fwd/bwd/wrw

test/CMakeLists.txt
The bug is originated from my PR #1246 (which is unsuccessful attempt to fix another problem with MLIR testing). Currently many custom tests (including new test_regression_half_mi200) are not working.
=> [HOTFIX] Fix issue: Custom tests that do not have MLIR_ENABLED are disabled by default

src/include/miopen/solver.hpp, src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_perf_config.cpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
This PR updates the Performance config for the ASM Implicit GEMM solvers where the deserialize protocol does not correctly read back the precision.
These code changes were drafted by @atamazov I have validated the fix on the target architecture.
=> [gfx90a]Fix an issue in the Asm IGEMM dynamic solvers Perf Config

CMakeLists.txt, Dockerfile, Jenkinsfile, mlir-requirements.txt, requirements.txt, test/CMakeLists.txt
This PR implements https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/57. I made the following changes:
- In Jenkinsfile
- Toggled `mlir_build` to be default on to pull in mlir dependencies
- Toggled `-DMIOPEN_USE_MLIR` to be default on to build with MLIR support
- In test/CmakeLists.txt
- Toggled `MIOPEN_USE_MLIR` to be default on if not specified
- Bumped mlir commit to the latest
=> [MLIR] Making MIOpen build and test MLIR by default

CMakeLists.txt, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_wrw.cpp, test/CMakeLists.txt
This is to capture a few optimizations I talked with @atamazov offline:
- Disable non-xdlops kernels from picking up on gfx908 (or gfx90a) to reduce compilation overhead
- Add cmake error string to remind user to reinstall dependencies
=> [MLIR] Adding misc optimizations

requirements.txt
The enhancement is to use recipe instead of raw url to install sqlite3
sqlite3 is required dependency of MIOpen, as listed in requirements.txt
=> [Enhancement] Use recipe instead of raw url to install sqlite3

src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp
This is leftover from #1258. Resolves https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1258#issuecomment-984860960
=> [HOTFIX][gfx90a][FP16] Disable ConvCkIgemmFwdV6r1DlopsNchw when "ALT FP16" kernel is required

src/conv/invokers/impl_gemm_dynamic.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
root cause fix for swdev312112:
[nchw]fix local buffer alignment bug on transpose+nhwc kernel's solver.
_added by carlus:_
````
original buffer       workspace
inp NCHW fp16  --> 1# inp NHWC fp16 buffer
wei NCHW fp16  --> 2# wei NHWC fp16 buffer
out NCHW fp16  --> 3# out NHWC fp16 buffer
4# out NHWC fp32 buffer  <- bug here
````
Above is what we are implementing in fwd when input is NCHW but use NHWC kernel with transpose. Basically there should be 4 buffers in workspace, where the first 3 buffers are for transpose the original inp/wei/out buffer. the last one is for some kernel that need use atomic fp32 to accumulate the result, then cast back to fp16. We always allocate a single workspace, and keep an offset inside each of the buffer.
So the problem here is the offset for 4# may not be …
=> [NCHW][SWDEV-312112] fix local buffer alignment bug on transpose+nhwc kernel's solver

src/comgr.cpp
This switches off the W/A for [SWDEV-308265 "[COMGR] Precompiler headers are broken: __hipGetPCH() is not available.."](https://ontrack-internal.amd.com/browse/SWDEV-308265) introduced in #1243 starting from HIP version 5.0.0.
:warning: The fix in ROCClr present in Mainline since build 9292. However, the build reports HIP version 4.4.21493. In order to test PCH functionality in the Mainline, it is necessary to provide two additional options to MIOpen's CMake command line:
```
... -DMIOPEN_OVERRIDE_HIP_VERSION_MAJOR=5 -DMIOPEN_OVERRIDE_HIP_VERSION_MINOR=0 ...
```
Locally tested.
:warning: Similar PR needs to be prepared for 4.5.x (if 4.5.x with fix for missing `__hipGetPCH()` will be released).
=> [HIP][COMGR] Re-enable PCH starting from 5.0 (SWDEV-308265 is fixed in ROCClr)

src/include/miopen/solver/conv_direct_naive_conv.hpp, src/solver/conv_direct_naive_conv.cpp, src/solver/conv_direct_naive_conv_bwd.cpp, src/solver/conv_direct_naive_conv_fwd.cpp, src/solver/conv_direct_naive_conv_wrw.cpp
This is fix of #1319 for the 4.5 release staging branch required by Frameworks team.
=> [ROCm4.5] Fix: Use `use_hip_kernels` and `use_asm_kernels` in Naive convolution Solvers

src/hipoc/hipoc_program.cpp, src/ocl/clhelper.cpp, test/CMakeLists.txt
Partially reverts #1336.
This should be merged only if necessary. i.e. if:
- SWDEV-292187 continues to reproduce with current Staging (amd-develop 8d400b378)
- Exporting `MIOPEN_DEBUG_OPENCL_WAVE64_NOWGP=0` resolves it with current Staging.
=> [HOTFIX][Navi21][SWDEV-292187] Do not enforce WAVE64 mode for all OpenCL kernels by default. Restored W/A for #1148.

test/CMakeLists.txt
Resolves #1351 and unblocks CI (the failures are random).
=> [tests] Disable test_regression_opencl_float_mi100 if WORKAROUND_ISSUE_1317 is set.

requirements.txt, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_wrw.cpp, test/CMakeLists.txt
Per request according to https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/389
I made the following changes:
- Bump MLIR commit to the ROCm 5.1 release commit
- Disable gfx900 from non-xdlops solvers
- Disable gfx900 from ctest
- Split `MIOPEN_TEST_VEGA` to `MIOPEN_TEST_GFX900` and `MIOPEN_TEST_GFX906`
- Add `GFX900_DISABLED` to `test_conv_igemm_mlir*`
=> [MLIR] Disable gfx900 from non-xdlops solver

src/include/miopen/any_solver.hpp, src/include/miopen/find_solution.hpp, src/include/miopen/solver.hpp, src/mlo_dir_conv.cpp, src/ocl/convolutionocl.cpp
- Optimizes GWSS for DYNAMIC_HYBRID mode
- Optimize out `IsApplicable()` calls when workspace is not necessary for a Solver
- `MayNeedWorkspace()` is introduced in the [Solver API](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/866#issuecomment-822585406) for that.
- By-products
- Refactor GetWorkspaceSize -> GetWorkspaceSizes for clarity
- Immediate mode API (`miopenConvolutionForwardGetSolutionWorkspaceSize` etc): 15...115% 
- Find API (`miopenConvolutionForwardGetWorkSpaceSize` etc): 2...17%
However the overall effect on the total Aux Wall Time (that includes GWSS time) is relatively small and does not exceed 2%.
The total GWSS time for the use case described at #1297 is progressed from ~24 to ~7 ms.
:warning: This may camouflage the visibility of #1297 during GWSS calls. So …
=> [conv] Optimize performance of GWSS

src/hipoc/hipoc_program.cpp, src/include/miopen/temp_file.hpp, src/ocl/gcn_asm_utils.cpp, src/temp_file.cpp, test/perfdb.cpp
Quick W/A for issue #1359, almost identical to https://github.com/AMDComputeLibraries/MLOpen/pull/2501.
=> [WORKAROUND][COMGR] W/A for issue 1359: Use hipModuleLoad with interim file instead of hipModuleLoadData. By-product: Better names for tempfiles.

Jenkinsfile, include/miopen/config.h.in, src/CMakeLists.txt, src/find_controls.cpp, src/include/miopen/find_controls.hpp, src/include/miopen/miopen_internal.h
MIOPEN_DEFAULT_FIND_MODE cmake variable maybe used to override the default MIOpen find mode. 
This is #1347 for `develop`.
=> Allow setting the default FIND_MODE at CMake configuration phase

src/hip/hip_build_utils.cpp
This won't change anything for ROCm <= 4.3 (including our current CI). It is highly unlikely, but this _may_ affect performance of MI100/200 on ROCm 4.5.x and 5.0.
=> [HOTFIX][WORKAROUND] Resolve SWDEV-317745

src/CMakeLists.txt
Pulled in the most recent version of FIN https://github.com/ROCmSoftwarePlatform/fin:
- contains JSON versioning
=> [TUNA] FIN subtree updates JSON versioning

test/ford.hpp
We currently use ```std::accumulate(lens.begin(), lens.end(), 1, std::multiplies<std::size_t>())``` to determine a ```for``` loop's max size. As per https://en.cppreference.com/w/cpp/algorithm/accumulate, std::accumulate will use type of init as a return data type. When we use immed num ```1``` as init, the return var will be deduced as ```int``` type. However, ```lens``` is a vector of ```std::size_t```, when multiply of each item in ```lens``` is larger than max value of ```int```, a ```for``` loop will get a weird num like ```-2147483648```, which will cause a dead loop.
When we run:
```
./bin/MIOpenDriver conv -n 4096 -c 1 -H 512 -W 1024 -k 1 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 1 -t 1 -w 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
```
host code will run a …
=> [host code]fix a host static for loop bug

src/conv/invokers/impl_gemm_dynamic.cpp, src/include/miopen/conv/asm_implicit_gemm.hpp, src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp, test/CMakeLists.txt, test/ford.hpp
[asm igemm][NHWC]
Fix solver bug when input/output tensor is over 4GB.
test cases:
```
export MIOPEN_DEBUG_FIND_ONLY_SOLVER="ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC;ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC;ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC"
make -j test_conv2d
./bin/test_conv2d --float --cmode conv --pmode default --group-count 1 --disable-backward-weights --disable-backward-data --disable-verification-cache -v --input 4096 1 512 1024 --weights 1 1 1 1 --batch_size 4096 --input_channels 1 --output_channels 1 --spatial_dim_elements 512 1024 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
./bin/test_conv2d --float --cmode conv --pmode default --group-count 1 --disable-backward-weights …
```
=> [SWDEV-316198] add split_4g_func in asm igemm bwd solver

src/solver/batchnorm/backward_spatial_single.cpp
This is #1386 ported to 5.0 release branch.
This fix addresses Batchnorm backward precision issues. Manually tested on gfx906 and gfx1030, including:
```
./bin/test_bn_3d_spatial_test --half --all
./bin/test_bn_spatial_test --half --all
./bin/MIOpenDriver bnormfp16 -n 256 -c 1024 -H 14 -W 14 -m 1 --forw 0 -b 1 -r 1
./bin/MIOpenDriver bnormfp16 -n 256 -c 1024 -H 14 -W 14 -m 1 --forw 1 -b 0 -s 1 -r 1
./bin/MIOpenDriver bnormfp16 -n 256 -c 2048 -H 7 -W 7 -m 1 --forw 0 -b 1 -r 1
./bin/MIOpenDriver bnormfp16 -n 256 -c 2048 -H 7 -W 7 -m 1 --forw 1 -b 0 -s 1 -r 1
./bin/MIOpenDriver bnormfp16 -n 256 -c 256 -H 56 -W 56 -m 1 --forw 0 -b 1 -r 1
./bin/MIOpenDriver bnormfp16 -n 256 -c 256 -H 56 -W 56 -m 1 --forw 1 -b 0 -s 1 -r 1
./bin/MIOpenDriver bnormfp16 -n 256 -c 512 -H 28 -W 28 -m 1 --forw 0 -b 1 …
```
=> [5.0][Navi21] Fixing Batchnorm backward precision issues by adjusting workgroup size (SWDEV-292187, SWDEV-319919)

src/solver/conv_asm_1x1u_bias_activ.cpp
Clone of #1395 for 5.0 release.
This PR reverts an incorrect code commit introduced in #1221 which disables search for the `ConvBiasActivAsm1x1U` solver
=> [Release][5.0] Revert incorrect change to ConvBiasActivAsm1x1U solver search method

src/execution_context.cpp, src/include/miopen/execution_context.hpp, src/include/miopen/target_properties.hpp, src/solver/conv_ocl_dir2D11x11.cpp, src/solver/conv_ocl_dir2D_bwdWrW_1x1.cpp, src/solver/conv_ocl_dir2D_bwdWrW_2.cpp, src/solver/conv_ocl_dir2D_bwdWrW_53.cpp, src/solver/conv_ocl_dir2Dfwd.cpp, src/solver/conv_ocl_dir2Dfwd1x1.cpp, src/solver/conv_ocl_dir2Dfwdgen.cpp, test/CMakeLists.txt, test/handle_test.cpp
This is the clone of #1390 for develop.
**_This is alternative for #1353_** which removes W/A for SWDEV-292187 completely instead of narrowing it, thus restoring both FP16 and FP32 performance for Navi21.
=> [Navi21] Remove W/A for SWDEV-292187

src/solver/conv_asm_1x1u_bias_activ.cpp
This PR reverts an incorrect code commit introduced in #1221 which disables search for the `ConvBiasActivAsm1x1U` solver
=> Revert incorrect change to `ConvBiasActivAsm1x1U` solver search method

driver/conv_driver.hpp, driver/lrn_driver.hpp, driver/reduce_driver.hpp, driver/softmax_driver.hpp
A lot of places:
```
if(error > tolerance)
{
std::cout << "verification Failed ";
}
```
will have issue if error contains NaN; per IEEE-754 the comparison will return FALSE.
=> [Quality] Fix potential verify error with NaN - IEEE-754 comparison rule

src/include/miopen/solver/conv_direct_naive_conv.hpp, src/solver/conv_direct_naive_conv.cpp, src/solver/conv_direct_naive_conv_bwd.cpp, src/solver/conv_direct_naive_conv_fwd.cpp, src/solver/conv_direct_naive_conv_wrw.cpp, test/find_db.cpp
this fix https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1319
=> Fix: Use `use_hip_kernels` and `use_asm_kernels` in Naive convolution Solvers

src/composable_kernel/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_second_call_threadwise_reduce_all_dims.cpp, src/reducetensor.cpp, test/CMakeLists.txt
Quick fix for [SWDEV-321331](https://ontrack-internal.amd.com/browse/SWDEV-321331). 
The fix has been verified with the following script using MIOpenDriver. 
```bash
#!/bin/bash
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 8,2,1 -I 0 -N 1 -O 0 -R 0,1,2
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 160,10,1 -I 0 -N 1 -O 0 -R 0,1,2
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 7,1024,1 -I 0 -N 1 -O 0 -R 0,1,2
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 1024,30528,1 -I 0 -N 1 -O 0 -R 0,1,2
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 3,1,1 -I 0 -N 1 -O 0 -R 0,1,2
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 3,1,1 -I 0 -N 1 -O 1 -R 0,1,2
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 3,1,1 -I 1 -N 1 -O 3 -R 0,1,2
./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 3,2,1 -I 1 -N 1 -O 3 -R 1,2
./bin/MIOpenDriver …
```
=> [SWDEV-321331] Fix ONNX runtime unit tests for reductions

test/CMakeLists.txt, test/reduce_test.cpp
Resolves [Issue 1410](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1410)
Update in test/reduce_test.cpp to make the leaked testing case mentioned in [PR.1409 ](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1409) as well as [Issue 1410](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1410) pass.  The fix has passed all MIOpenDriver and test_reduce_test cases used in [PR.1409 ](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1409) as well as the case
`./bin/test_reduce_test --scales 1 0 --CompType 1 --D 1024 30528 1 --I 0 --N 1 ---ReduceOp 0 --R 0 1 2 -v`
Also, the following default test_reduce_test batch tests passed 
`./bin/test_reduce_test --all`
`./bin/test_reduce_test --all --half`
`./bin/test_reduce_test --all --double`
=> [Tests] add test_reduce_test and follow up PR #1409

src/kernels/MIOpenLRNBwd.cl
Fixed a NAN issue by providing a fix to synchronize local memory access within workgroup in LRN (local response normalization) layer.
=> [SWDEV-274378][LRN] Fix in local response normalization layer to synchronize local memory access within workgroup

Jenkinsfile
- Do not require clinfo for NOGPU test stages.
- This avoids failures of NOGPU stages on nodes that do not have GPU installed.
- KFD is still required on the nodes.
- Do not reboot nodes after NOGPU jobs (to save time).
- Remove `no_reboot` parameter as it is no longer used.
=> [Jenkinsfile][NOGPU] Do not use clinfo and do not reboot nodes.

test/CMakeLists.txt
Issue described in #1423:
We still need to fix the issue, this PR is to unlock develop branch
Hence: not reverting #1415 since it worked for FP32
=> [Tests][Navi21][FP16] W/A #1423 bypass large tensor reduce test

.gitignore, driver/bn_driver.hpp, driver/conv_driver.hpp, driver/ctc_driver.hpp, driver/dropout_driver.hpp, driver/gemm_driver.hpp, driver/lrn_driver.hpp, driver/pool_driver.hpp, driver/reduce_driver.hpp, driver/rnn_driver.hpp, driver/softmax_driver.hpp
Update: fixed a few extra places where the comparison might have issues.
Original Comments about the root cause:
A lot of places:
```
if(error > tolerance)
{
std::cout << "verification Failed ";
}
```
will have issue if error contains NaN; per IEEE-754 the comparison will return FALSE.
=> [Quality] Fix more verify error with NaNs and Inf

include/miopen/miopen.h, src/tensor_api.cpp, test/tensor_api.cpp
This PR adds the new `miopenSet4dTensorDescriptorEx ` API as required by issue #1430 .
=> [API] Implement miopenSet4dTensorDescriptorEx for cuDNN parity

include/miopen/miopen.h
fix #1452, by running `clang-format-10 -style=file -i  ./include/miopen/miopen.h`
=> [HOTFIX] fix miopen.h clang-format-10

include/miopen/miopen.h, src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp, src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_bwd_xdlops.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp, src/solver/conv_mlir_igemm_wrw.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp
This is an hot fix for [SWDEV-316705](https://ontrack-internal.amd.com/browse/SWDEV-316705)
Due to our current design, if a solver has multiple configs, and some of the config support deterministic(e.g. non-deterministic), some are not, we can not disable a single config in `IsValid()` function. But We need disable it in `IsApplicable()`, which means will disable this solver entirely if `MIOPEN_DEBUG_CONVOLUTION_DETERMINISTIC` env var is set.
This may have a performance impact, but since currently this env var is for test purpose (in this case performance impact is OK per our customer), so this approach is simple and fine.
If in future has performance requirement under `MIOPEN_DEBUG_CONVOLUTION_DETERMINISTIC`, need to seek for other approach and implementation.
=> [HOTFIX][SWDEV-326460] check MIOPEN_DEBUG_CONVOLUTION_DETERMINISTIC in IsApplicable()

requirements.txt, src/conv/invokers/mlir_impl_gemm.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp
MLIR implementation is now capable of producing these utility kernels. Eliminate the dependency to OpenCL-based kernels in MIOpen.
This PR only address wrw. A subsequent PR will change the same for bwd kernel invocations.
This PR depend on #1443 be merged first.
=> Eliminate dependency to SetTensor/CastTensor in MLIR XDLOPS wrw solver.

src/conv/invokers/impl_gemm_dynamic.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd.cpp, src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp, src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp, src/solver/conv_asm_implicit_gemm_wrw_gtc_dynamic_xdlops.cpp, test/CMakeLists.txt
To solve #1495 .
In bwd solver, we re-compute the ```stride_h``` and ```stride_w``` by the following code:
```
const auto stride_h   = ctx.in_height > 1 ? ctx.kernel_stride_h : 1;
const auto stride_w   = ctx.in_width > 1 ? ctx.kernel_stride_w : 1;
```
However, MIOpen switches input size and output size for backward path. So we need the following code to get the right params. 
```
const auto stride_h   = ctx.out_height > 1 ? ctx.kernel_stride_h : 1;
const auto stride_w   = ctx.out_width > 1 ? ctx.kernel_stride_w : 1;
```
test case:
./bin/MIOpenDriver conv -n 256 -c 2048 -H 2 -W 2 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 2 -t 1 -w 1
=> [Bug fix][SWDEV-329914] fix stride compute bug in asm igemm bwd fwd and wrw

src/kernels/Conv_Winograd_v21_1_3_gfx90a_f3x2_fp16_dot2_edc_stride1_group.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_f3x2_fp32_stride1_group.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_dilation2.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_dilation2_group.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride1.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride1_group.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride2.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp16_dot2_edc_stride2_group.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_dilation2.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_dilation2_group.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride1.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride1_group.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride2.inc, src/kernels/Conv_Winograd_v21_1_3_gfx90a_fp32_stride2_group.inc
This PR:
- Updates Winograd v21_1_3 kernels for gfx90a to match the development sources.
- Fixes mismatched Winograd v21_1_3 f3x2 implementation for gfx90a (previously used f2x3 instead of f3x2 implementation).
- rocm 5.0.2, gfx90a
=> [GFX90A] Winograd 21_1_3 minor updates

requirements.txt, test/CMakeLists.txt
We have branched and enabled MI200 in our local testing. I bump the release branch as well as enabled gfx90a testing in MIOpen end.
In summary, if everything goes well, we'd need both https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1435 and this PR in to make it ROCm 5.2.
=> [MLIR] Bumping release to ROCm 5.2

CMakeLists.txt
When HIPRTC is enabled the runtime compilation is performed through
hiprtc and comgr apis. So rocm-clang-ocl dependency can be removed.
However if HIPRTC is disabled it adds the clang-ocl dependency
to the miopen-hip package conditionally..
Signed-off-by: Saravanan Solaiyappan <saravanan.solaiyappan@amd.com>
=> [SWDEV-329485] Remove clang-ocl dependency for miopen-hip

test/CMakeLists.txt
This finally resolves #898. Additional info:
- https://github.com/ROCmSoftwarePlatform/MIOpen/issues/898#issuecomment-1036629696
- https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1469#issuecomment-1076778427
=> [tests] Enabled PCH for testing builds that have COMGR enabled (removed WORKAROUND_ISSUE_898)

src/gemm_v2.cpp, src/include/miopen/handle.hpp
- Updated rocblas include path. 
- Fix internal build warning (reorg deprecated version warnings)
=> Fix Warning - Update rocBLAS re-org PATH

src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp
In MLIR solver, I discovered a bug where, applicability check and get solution ended to get different result. The reason ended up being we only query the first kernel's applicability in MLIR whereas second kernel is in-applicable.
In this PR, I fixed this issue by making performance config to mark as applicable only when all subsequent kernels are applicable.
=> [MLIR] Querying all sub-kernels applicability

dev-requirements.txt, requirements.txt
- Updated latest rocm-cmake version requirement for reorg changes
- This version has changes for rocm-cmake Only link library specific files (https://github.com/RadeonOpenCompute/rocm-cmake/pull/84)
=> Updated rocm cmake version requirement 

src/CMakeLists.txt
This provides separate lists for in development kernels and kernel includes. Using them instead of main lists should significantly reduce rebuild time when changing the kernel source. At the end of the kernel development cycle (before merging the PR) they should be moved to main lists to free up build time. This is a fix for our unity build like kernel inline process.
Additional build time reduction may be reached if kernel references were added to a separate map as the main map file would not require regeneration and rebuild.
This PR is probably worth being noted to kernel developers who are/would like to try iterating their sources in the MIOpen itself.
=> [kernel references List]Development kernel and kernel include batches

driver/conv_driver.hpp, driver/main.cpp
This PR makes MIOpenDriver's int8 convolution output native type to be int32, based on:
- MIOpen's gemm is based on rocblas, whose int8 output type is int32
- There's an unnecessary `CastTensor` operation forced in every int8 validation
- More fundamentally, AMD XDLOPS instructions output type for int8 calculation is int32
- This implied high performance kernel will pick int32 as the native output type 
- Numerical precision has been compromised by forcing conversion from int32 to fp32
- Not all int32 can be precisely converted, see [here](https://stackoverflow.com/questions/12442685/can-a-ieee-754-real-number-cover-all-integers-within-its-range)
- fp32 type incorrectly becomes the first class citizen for int8
- If there's a solver who can support only int32 as the output, it will be …
=> Make int8 convolution default output type to be int32

dev-requirements.txt, requirements.txt, src/CMakeLists.txt
- Update ROCM-CMAKE Version
- Enable original file dump option for wrapper header to support backward compatibility
=> [ROCm-cmake] Enable Origin header file dump option for wrapper

src/composable_kernel/composable_kernel/include/utility/config.hpp, src/include/miopen/solver/ck_utility_common.hpp, src/include/miopen/solver/implicitgemm_util.hpp, src/kernels/MIOpenBatchNormActivBwdPerAct.cl, src/kernels/MIOpenBatchNormActivBwdSpatial.cl, src/kernels/MIOpenBatchNormActivFwdTrainSpatial.cl, src/kernels/MIOpenBatchNormBwdSpatial.cl, src/kernels/MIOpenBatchNormFwdTrainSpatial.cl, src/kernels/batchnorm_functions.h, src/md_graph.cpp, src/ocl/fusionopbiasbnactivocl.cpp, src/solver/batchnorm/backward_per_activation.cpp, src/solver/batchnorm/backward_spatial_multiple.cpp, src/solver/batchnorm/backward_spatial_single.cpp, src/solver/batchnorm/forward_inference.cpp, src/solver/batchnorm/forward_per_activation.cpp, src/solver/batchnorm/forward_spatial_multiple.cpp, src/solver/batchnorm/forward_spatial_single.cpp, test/CMakeLists.txt, test/handle_test.cpp, test/mdgraph.cpp
~* CK-specific tests are allowed to fail on gfx103X except gfx1030~
~:question: **_TODO enable gfx1031 in CK._** Unofficial support could be handy for our new users and this should be easy to do. @qianfengz @asroy @junliume what do you think? If we are not going to support it, then it may worth reverting changes in tests.~
=> Unofficially support gfx1031.

dev-requirements.txt, requirements.txt, src/CMakeLists.txt
Summary of proposed changes:
- Original Header File Dump enabled for version header file wrapper to support backward Compatibility for PT/TF
- Depends on wrapper functions of rocm-cmake version https://github.com/RadeonOpenCompute/rocm-cmake/commit/d108dbf05e029996d5d7bcbe258abb1166547a30
=> Enable Original File Dump in Version Header File Wrapper for backward compatibility

requirements.txt, src/conv/invokers/mlir_impl_gemm.cpp, src/include/miopen/conv/problem_description.hpp, src/include/miopen/problem_description.hpp, src/mlo_dir_conv.cpp, src/ocl/convolutionocl.cpp, src/solver/mlir_common.cpp, test/CMakeLists.txt, test/conv_common.hpp
This PR enables `ConvMlirIgemmFwdXdlops` solver for int8 convolutions on following types:
- int8 x int8 x int32
- int8 x int8 x fp32
This PR made the below changes:
- Bumped MLIR commit id to the latest, which has support for int8 convolution
- Added `IsInt8()` call in problem description, making int8 have parallel support to other types
- This help fix the "Unsupported data types configuration" warnings from `mlo_dir_conv.cpp`
- Relaxed the restriction of non-gemm solver for in8 type in `convolutionocl.cpp`
- Added a `CastTensor` kernel upon MLIR int8 invoker such that it allows non-int32 output type
- Amended `conv2d_test`, such that all fwd convolutions are int8 enabled
- Got rid of the `conv2d_test` requirement that a solver supporting int8 must also support int8x4
- TODO: Add an …
=> [MLIR] Adding int8 support and test to ConvMlirIgemmFwdXdlops solver

CMakeLists.txt
Issue with SRIOV should have been resolved and root cause has identifies to be not MIOpen.
We should re-enable hipRTC as default
The original PR which disabled hipRTC is https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1470
=> Enable hipRTC as default

CMakeLists.txt, src/kernels/gpu_reference_kernel/naive_conv.cpp
Sorry I broke the develop line (hence the [HotFix]
hipRTC enablement has conflict with #1544, where it will compalin *error: unknown type name 'int8_t'*
Reminder for @atamazov to review if interested
=> [HotFix] Resolve int8_t type with hipRTC workaround

driver/conv_driver.hpp
hot fix issue #1564 
Without this PR, our `MIOpenDriver` will fail every time you launch the driver
cc @aska-0096 @atamazov @Slimakanzer
=> [Hotfix][Issue 1564] Fix Conv Driver Failure with default vector_length parameter

test/cpu_conv.hpp
fix issue https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1566
Basically this is due to acc_type selection is not correct, introduced by PR:#1544.
This will block all `MIOpenDriver` cpu validation.
=> [HotFix][Issue 1566][gfx10] fix verification issues

CMakeLists.txt
We do not need clang-ocl when we have COMgr enabled. Details at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1492#pullrequestreview-989589625.
Enhancement, urgency: normal.
=> [Dependency] Do not require clang-ocl when COMgr is enabled

driver/conv_driver.hpp, driver/driver.hpp
Problem and solution described in #1576 
Summary: caused by the way to construct the host tensor which used to hold the gpu reference data.
cc: @atamazov
=> [HotFix][Issue 1576] Fix bwd conv gpu reference bug

CMakeLists.txt, include/miopen/config.h.in, speedtests/sequences.cpp, src/gemm_v2.cpp, src/include/miopen/find_db.hpp, src/include/miopen/handle.hpp, src/include/miopen/op_kernel_args.hpp
- `WORKAROUND_BOOST_ISSUE_392`
- Note: For more info about issue, see #1489
- Uniformly marked in comments (now easy to grep)
- Fix: W/A moved under guard in config.h
- Resolves https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1543#discussion_r889131708
- W/A added to speedtests/sequences.cpp instead of W/A + "puzzling W/A" in op_kernel_args.hpp
- See https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1543#discussion_r873109516
- rocBLAS version
- Print from CMake
- Uniformly provided in config.h as macros (`MIOPEN_ROCBLAS_VERSION_*`)
- Refactor: Replaced old stuff with new version macros
- Tweak for inclusion of `rocblas.h` for ROCm 5.2
- Fix: Use rocBLAS version (2.45) instead of HIP (5.2) version to detect
- Why 2.45: https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/99528dd091 …
=> Refine PR #1543 and more

driver/lrn_driver.hpp, src/kernels/MIOpenLRNFwd.cl, test/lrn_test.cpp
This PR fixes #1559 and adjusts initialization of the input data in `MIOpenDriver` for LRN and `test_lrn_test` to test the cases when input contains negative values.
=> [LRN] fix incorrect sign in output

src/mlo_dir_conv.cpp
This workaround causes `MIOPEN_FIND_MODE` to behave incorrectly when set to `1`. The underlying issue of slow startup times is no longer relevant since the default find mode for MIOpen is `5` resulting in a search only along dynamic solvers.
=> [Enhancement] FIND_MODE 1 - remove workaround for SWDEV_227826

src/solver/conv_asm_dir_BwdWrW3x3.cpp
Workaround for [SWDEV-330460](https://ontrack-internal.amd.com/browse/SWDEV-330460)
=> [SWDEV-330460][W/A][gfx90a][FP32] disable ConvAsmBwdWrw3x3 for numerical stability

requirements.txt
Regression tests have all passed for ROCm 5.3.0 tag. Pushing this as MLIR go to development complete.
=> [MLIR] Bumping release tag to rocm-5.3.0

test/CMakeLists.txt
Follow-up to https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1539
After supports for xdlops/nonxdlops for int8 added, only xdlops testing has been added for the previous PR. I'm adding the non-xdlops testing as well such that it get tracked in MIOpen CI. Now both forward test has `INT8_ENABLED` flags in them.
=> [MLIR] Enable nonxdlops conv fwd tests for int8

src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
w/a swd306318:
kernel produce wrong result using:
```
MIOpenDriver conv -n 16 -c 76 -H 9 -W 9 -k 32 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 -w 1
```
As kernel was developed about 2 years ago and I was not the developer, I need more time to identity the faulty code block. In order to move the test process forward, I give a w/a at this moment and I will continue checking the root cause.
As MIOpen has nhwc+transpose kernel as backup, it will not broke anything by disabling this solver.
=> [SWDEV-306318][WORKAROUND][gfx908] Disable ConvAsmImplicitGemmGTCDynamicFwdXdlops

test/CMakeLists.txt
Updated test/CMakeLists.txt to exclude two GPU dependent tests on non-GPU platform.
=> [noGPU] Updated CMakeLists to exclude GPU dependent tests on NO GPU platform

test/CMakeLists.txt
in PR #1619 we disable `ConvAsmImplicitGemmGTCDynamicFwdXdlops`, but not close it in ctest. This will cause issue #1638 .This PR is a hot fix for issue.
=> [HOTFIX] disable ctest for ConvAsmImplicitGemmGTCDynamicFwdXdlops 

src/solver/conv_winoRxS.cpp
This PR fixes incorrect `ConvBinWinogradRxSf2x3`  applicability introduced in #1533.
=> [BugFix] Winograd ConvBinWinogradRxSf2x3 applicability

CMakeLists.txt
https://ontrack-internal.amd.com/browse/SWDEV-257567
created miopen-lib.support@amd.com for the MIOpen libraries: miopen-hip, miopen-opencl, and miopengemm
=> [NFC][SWDEV-257567] Update distribution list maintainer/contact

src/solver/conv_asm_dir_BwdWrW3x3.cpp
Improvement of W/A introduced in #1616: this allows to enable ConvAsmBwdWrw3x3 explicitly by means of `MIOPEN_DEBUG_CONV_DIRECT_ASM_WRW3X3`. Might be useful for experimentation when developing the full-blown fix.
=> [SWDEV-330460] Improve workaround for ConvAsmBwdWrw3x3

test/CMakeLists.txt
Closes #1053 as not reproducible.
- Tested with 5.0, HIP and OCL backends.
- `WORKAROUND_ISSUE_1053` to be removed during routine cleanup after some time.
@junliume @xinlipn Please review.
=> [tests][Navi21] Disable WORKAROUND_ISSUE_1053 as issue is not reproducible.

src/kernels/MIOpenIm2d2Col.cl, src/ocl/utilocl.cpp
FIX for #1621 
Fixed bug with buffer index bigger than int32.
Fixed last part of kernel code, EXTREME_LARGE==1.
Tested configs:
```
export MIOPEN_FIND_MODE=1
export MIOPEN_DEBUG_FIND_ONLY_SOLVER=GemmFwdRest
./bin/MIOpenDriver convfp16 -W 300 -H 100 -c 1024 -n 1 -k 4 -x 256 -y 256 -p 0 -q 0 -u 1 -v 1 -F 1 -t 1 -V 1 -l 2
./bin/MIOpenDriver convfp16 -W 63 -H 135 -c 2040 -n 1 -k 16 -x 32 -y 128 -p 0 -q 0 -u 1 -v 1 -F 1 -t 1 -V 1
./bin/MIOpenDriver convfp16 -W 63 -H 135 -c 2050 -n 1 -k 16 -x 32 -y 128 -p 0 -q 0 -u 1 -v 1 -F 1 -t 1 -V 1
./bin/MIOpenDriver convfp16 -W 1760 -H 1760 -c 80 -n 1 -k 16 -x 3 -y 3 -p 0 -q 0 -u 1 -v 1 -F 1 -t 1 -V 1
./bin/MIOpenDriver convfp16 -W 1760 -H 1760 -c 75 -n 1 -k 16 -x 3 -y 3 -p 0 -q 0 -u 1 -v 1 -F 1 -t 1 -V 1
```
=> [BugFix] MIOpenIm2d2Col.cl kernel: fix address calculation

src/solver/pooling/backward2d.cpp
This fixes a typo in the original PR causing incorrect values to be passed for any asymmetric parameter combinations in one of backward solvers.
=> [SWDEV-345750] Fix Tensorflow pooling test failure

driver/conv_driver.hpp
Fix for #1653 
Change the tensor constructor to avoid datatype not match error when construct the destination host tensor.
=> [Hotfix] Issue 1653, Inappropriate Host API usage 

test/CMakeLists.txt
This resolves issue #1405. Manually tested under the followign conditions:
- gfx906, gfx1030
- BN fp32, BN fp16
- Jest before #1386, just after #1386, current tip of develop
@junliume @ce1adon @muralinr Please review.
=> [tests][Navi21][BN] Leftover of #1386 - add regression tests

src/ocl/handleocl.cpp
Since most of our known clients use the AMD HIP based backend for managing code  objects and launching kernels, the MIOpen team has decided to deprecate the OpenCL backend. 
This PR adds a deprecation message to the OpenCL backend to inform users and gather input.
=> Add OpenCL deprecation Message

src/solver/conv_asm_implicit_gemm_gtc_fwd.cpp
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1619 originally try to fix SWDEV-306318, but introduced large performance regression.
This PR try to narrow down the non-applicable range, only when 1x1 conv, C is not multiple of 8, this solver is not applicable. This is true for both fp32 and fp16
cc @atamazov
=> [SWDEV-306318][WORKAROUND][gfx908] Limit WA PR:1619 by only ignore 1x1 conv where C is not 8x

CMakeLists.txt
remove extra warnings, by combining them into a single message
after:
```
CMake Warning at CMakeLists.txt:491 (message):
GIT LFS Files not pulled down, skipped: gfx90a68.kdb; gfx90a6e.kdb;
gfx1030_36.kdb; gfx90878.kdb; gfx906_64.kdb; gfx906_60.kdb; gfx900_64.kdb;
gfx900_56.kdb
```
before:
```
CMake Warning at CMakeLists.txt:468 (message):
GIT LFS Files not pulled down, skipping gfx90a68.kdb
Call Stack (most recent call first):
CMakeLists.txt:490 (install_kdb)
CMake Warning at CMakeLists.txt:468 (message):
GIT LFS Files not pulled down, skipping gfx90a6e.kdb
Call Stack (most recent call first):
CMakeLists.txt:490 (install_kdb)
CMake Warning at CMakeLists.txt:468 (message):
GIT LFS Files not pulled down, skipping gfx1030_36.kdb
Call Stack (most recent call first):
CMakeLists.txt:490 …
```
=> [Enhancement] remove extra warnings of KDB LFS from CMake

driver/tensor_driver.hpp, src/include/miopen/tensor.hpp, src/include/miopen/tensor_extra.hpp, src/tensor.cpp, src/tensor_api.cpp, test/CMakeLists.txt
#1661 Found that int type `vectorLength` in `TensorDescriptor` cause incorrect result of `TensorDescriptor::GetElementSize()` when construct big tensor size > 32bits, This PR simply change `vectorLength` and related "Get“ function return type to `std::size_t` to fix the overflow bug.
You can verify the fixing by using the same command in the issue ticket:
`./build/bin/MIOpenDriver conv -W 5078 -H 4903 -c 24 -n 5 -k 1 --fil_w 3 --fil_h 3 --pad_w 6 --pad_h 4 -F 1`
Or I strongly recommend you to add the MIOPEN_USE_GPU_REFERENCE=1 flag, since CPU verification takes long time on the big tensor convolution result.
`MIOPEN_DRIVER_USE_GPU_REFERENCE=1 ./bin/MIOpenDriver conv -W 5078 -H 4903 -c 24 -n 5 -k 1 --fil_w 3 --fil_h 3 --pad_w 6 --pad_h 4 -F 1`
cc: @atamazov
=> [TensorDescriptor][BugFix] Change vectorLength datatype to std::size_t

README.md
Add a section about Git LFS in readme. Listed the detailed steps to manage/store large files using Git LFS.
=> [Documentation] Add a section about Git LFS in readme

src/kernels/gfx90a68.kdb
Rocm5.3 mi210 (104 cu) find db tuning for all configs (140k) to create fdb and kdb
=> [ROCm 5.3][gfx90a68] Tuning updates of fdb and kdb key configurations

src/include/miopen/solver.hpp
PR removes unused performance configs: `PerformanceImplicitGemmV4R4GenXdlopsFwdFp32` and `PerformanceImplicitGemmV4R4GenXdlopsWrWFp32`
=> [Solvers] Remove unused performance configs

src/include/miopen/solver.hpp, src/solver/gemm_bwd.cpp
Workaround for https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/issues/59.
As in title, disables on backward gemm solver for MIOpenGEMM, which failes on CI.
This blocks #1503
=> [FP32] [miopengemm][Workaround] Disabled GemmBwd1x1_stride1

src/conv/invokers/mlir_impl_gemm.cpp
This is a companion PR to
https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/pull/690 and
should not be merged until that lands.
These changes will need to be revisited if the MLIR solver ever
supports dynamic shapes.
(I'm not entirely sure what to do about the unused args warnings)
=> [MLIR] Switch the ABI to use bare pointers and not memrefs

driver/mloConvHost.hpp, driver/mloPoolingHost.hpp
Ditto.
There were some copy-paste typos in validation, which caused errors in 3d pooling validation. Easily reproduceable with PR #1724.
I am not sure what value and urgency to place here, as it was only found out as side-effect of triaging other bug and it is a driver validation error, so it should not affect consumers.
Fixes #1660.
=> Fixed pooling 3d validation

src/solver/conv_winoRxS.cpp
WrW direction is only supported by grouped Winograd kernels (`ConvBinWinogradRxSf2x3` solver) and must be disabled for `ConvBinWinogradRxSf2x3g1` solver.
Perf/Find DB are not affected, but they will be affected once the full blown fix for #1681 is implemented.
=> [Proactive][Fix][Performance] Winograd applicability for WrW direction

fin/src/include/conv_fin.hpp, src/include/miopen/conv/context.hpp, src/include/miopen/convolution.hpp, src/include/miopen/mlo_internal.hpp, src/include/miopen/solver.hpp, src/ocl/convolutionocl.cpp, src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp
Dead code elimination.
`miopen::ConvolutionUserBuffers` was not used anywhere and only passed and initialized.
It has been spreading some confusion and even propagated around a bit.
=> [NFC] Removed miopen::ConvolutionUserBuffers

requirements.txt
This issue is due to a sha256 change to an existing archived tag in MLIR which is likely to be caused by a repository name change.
A quick workaround is to change the following line in `requirements.txt` in MIOpen when pulled: from
```
ROCmSoftwarePlatform/llvm-project-mlir@rocm-5.3.0 -H sha256:ee5093aad5459773c350205ef937a186a20994b42798106f8126b9914ad099a5 -DBUILD_FAT_LIBMLIRMIOPEN=1
```
To
```
ROCmSoftwarePlatform/llvm-project-mlir@rocm-5.3.0 -H sha256:e8471a13cb39d33adff34730d3162adaa5d20f9544d61a6a94b39b9b5762ad6d -DBUILD_FAT_LIBMLIRMIOPEN=1
```
In this case, we are removing the sha256 verification for a quick workaround
=> [HotFix][ROCm5.3.0] Patch MIOpen dependency on MLIR for sha256 verification

install_deps.cmake, rbuild.ini, requirements.txt
@JehandadKhan Thanks for the branch, this PR is needed to let `develop` passing builds on the docker images provided by CQE
1. Fix `pcre` dependency issue: the `cppcheck` version in Composable Kernel depends on an outdated URL of it, so we are ignoring it here; (BTW~ CK should be removing that dependency?)
2. Fix CK sync issue, when enabled, CK should provide the APIs expected from MIOpen.
=> [HotFix] Fix MIOpen dependencies build issues and sync CK version

src/include/miopen/handle.hpp
This PR fixes include guard name for handle.hpp
=> handle.hpp: fix include guard name

src/include/miopen/conv/context.hpp, src/include/miopen/solver.hpp, src/solver/conv_multipass_wino3x3WrW.cpp
List of changes:
- Implicit conversion from `ProblemDescription` to `ConvolutionContext` has been fixed
- `ConvolutionContext` constructor taking `ProblemDescription` has been marked `explicit` to avoid similar cases in the future (see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1778#pullrequestreview-1122522467)
=> [Solvers] ConvWinograd3x3MultipassWrW: fix implicit conversion

requirements.txt
All regression tests have passed for the rocm-5.4.0 tag.
=> [MLIR] Bumping release tag to rocm-5.4.0

src/conv/invokers/impl_gemm.cpp, src/include/miopen/conv/invokers/impl_gemm.hpp, src/include/miopen/solver.hpp, src/include/miopen/solver/implicitgemm_util.hpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v1r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r1.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_fwd_v4r5_xdlops.cpp, src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp, src/solver/conv_hip_implicit_gemm_nonxdlops_common.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops.cpp, src/solver/conv_hip_implicit_gemm_wrw_v4r4_xdlops_padded_gemm.cpp, src/solver/conv_hip_implicit_gemm_xdlops_common.cpp
List of changes:
- Preparation for splitting `ConvolutionContext` and `ProblemDescription` inside `ConvHipImplicitGemm` solvers
- `ConvHipImplicitGemmWrwV4R4Xdlops`: remove redundant `IsXdlopsSupport()`
=> [Solvers] ConvHipImplicitGemm solvers:  prepare for splitting ConvolutionContext and ProblemDescription (stage 2)

src/solver/conv_mlir_igemm_bwd.cpp, src/solver/conv_mlir_igemm_bwd_xdlops.cpp, src/solver/conv_mlir_igemm_fwd.cpp, src/solver/conv_mlir_igemm_fwd_xdlops.cpp, src/solver/conv_mlir_igemm_wrw_xdlops.cpp
This commit fixes the kernel count retrieval
to include perf_config used as part of the string
that is generated to pass to the Miir API.
Note this does not change the API per se but
includes extra information (additive) to passed
on to rocMLIR side.
=> Fixed MLIR kernel count retrieval

src/include/miopen/solver.hpp, src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
PR splits ConvolutionContext and ProblemDescription inside ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC
Additional changes:
- Missed `clang-format on` has been added, wrong code formatting has been fixed
- `inline` keyword has been replaced with `static` for `ComputeDynamicIGemmWrwKernelArgsNHWC()`
- `PerformanceConfigAsmImplicitGemmGTCFwdDlopsNCHWC:` unused function declarations have been removed
=> [Solvers] ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC: split ConvolutionContext and ProblemDescription (stage 2)
